### ISSUE TITLE
Webhook doesn't inform who made feature change

### ISSUE THREAD

**Issue by amandam11** [featurehub-io/featurehub#1016]
**Is your feature request related to a problem? Please describe.**
To see what feature value was changed and by who via the audit logs and webhooks is tricky. The information is there but not just in one place.

From the webhooks I am informed of what feature was changed, what to BUT NOT by whom. It would be useful if this also told me who made the change. This tells me both the dbfeaturevalue id but also the name of the feature and the application/porfolio/environment ids so I know easily which feature it is. It would be nice if this also said who did the change.
The  body for example has:
```
{"environment":{"environment":{"id":"48df9682-6de9-4562-8820-15d44059cd1f","version":4,"eInf":{"webhook.features.endpoint":"http://172.17.0.1:3000/appFeatureUpdate/MyPort/dummy/prd","webhook.features.enabled":"true"}},"oId":"8b929f46-ca76-4a62-888c-e273d685749a","pId":"4175f6fa-15ba-4db2-80e1-4e523efc5a3a","aId":"d6e94a16-bf04-4183-9200-b17537e9fb7e","fv":[{"feature":{"id":"94354073-8cd1-49eb-8a93-ccc028a3ccc3","key":"DUMMY_TEST","valueType":"BOOLEAN","version":1},"value":{"id":"b790168a-ab61-49a0-a806-ec86c5549e8f","key":"DUMMY_TEST","locked":false,"value":false,"version":7}}],"sa":["f030a821-5aca-4ad5-b3c7-4874fe5448d2"],"action":"UPDATE","c":1},"featureKeys":["DUMMY_TEST"]}
```

In the audit logs then the audit entry that tells me who made the change, tells me the old and new values and the dbfeaturevalue. But it is unclear from the logs which actually feature that it relates to, as it just tells me the dbfeaturevalue id, but it would be nice if that allowed me to see what the feature key was and applicaiton in similar way to the webhooks.

```
{"@timestamp":"2023-06-15T08:29:01.263+0000","message":"{\"ts\":1686817741261,\"change\":\"U\",\"type\":\"DbFeatureValue\",\"id\":\"b790168a-ab61-49a0-a806-ec86c5549e8f\",\"data\":{\"defaultValue\":\"true\",\"version\":8,\"whenUpdated\":\"2023-06-15T08:29:01.260\"},\"oldData\":{\"defaultValue\":\"false\",\"version\":7,\"whenUpdated\":\"2023-06-13T16:20:58.024\"}}","priority":"INFO","path":"io.ebean.ChangeLog","thread":"ebean-db13","host":"featurehub","user":{"id":"c8525978-d057-44f5-9521-0735b21171b1","email":"<user email>"}}
```

I can match the audit logs to which feature it was by using the adminSDK so I can tie up the information, but I have to get from two separate ways to get that information.
And to find out who made a change from a notification in a webhook, then I have only managed to find out who made that particular change by looking in the audit logs. I was unable to find out who made a particular change for a dbfeaturevalue id/version combination via the SDK. (Although I can find out last information, if this isn't the most recent change then I have only been able to find this by searching the logs.

{"@timestamp":"2023-06-13T16:20:58.025+0000","message":"{\"ts\":1686673258024,\"change\":\"U\",\"type\":\"DbFeatureValue\",\"id\":\"b790168a-ab61-49a0-a806-ec86c5549e8f\",\"data\":{\"defaultValue\":\"false\",\"version\":7,\"whenUpdated\":\"2023-06-13T16:20:58.024\"},\"oldData\":{\"defaultValue\":\"true\",\"version\":6,\"whenUpdated\":\"2023-06-13T16:19:01.808\"}}","priority":"INFO","path":"io.ebean.ChangeLog","thread":"ebean-db24","host":"featurehub","user":{"email":"amanda.mcguinness@tandem.co.uk","id":"c8525978-d057-44f5-9521-0735b21171b1"}}

**Describe the solution you'd like**
1. For the webhooks to also include the "user" who made the change, similar to what is in the DbFeatureValue audit log
2. For the audit entry for DbFeatureValue to also include the FEATURE key name and other information to make it easier to map
3. For the admin SDK to have a way of retrieving information about a particular feature / environment. So we could request for the history on a particular feature for a particular environment. Or even a way to request the details given a particular featurevalue and version number -> so we could find out who made a particular change.

**Describe alternatives you've considered**

**Additional context**

**Comment by IrinaSouth** [comment]
Hi Amanda,

Thanks for your clean and concise feedback and suggestions for changes. 

We had an internal discussion and we think that most of it we can implement fairly quickly. Will be posting updates here once there is a progress. 

Cheers, 
Irina

**Comment by rvowles** [comment]
So a couple of initial updates on this ticket. We discussed internally that we really need the TestSDK to be identifiable when it comes in and makes changes to feature values as well, currently these are transparent and don't turn up in the history. The transitioning of this field in feature value from being nullable -> not null was a wee bit of a mission in SQL and some post cleanup jobs, so we decided to introduce the "nil UUID" user to "blame" where we don't have the appropriate records.

The code for it is sitting here at the moment: https://github.com/featurehub-io/featurehub/pull/1017

and its passing our full end to end suite (which takes about an hour and a half to run) so far, but we need to add checks to make sure the user id is being correctly picked up for the testsdk. We have modified the "get person" API call to ensure that you can also get the Test SDK user.

Unfortunately for (2), the changelog is not under our control, it is part of the underlying framework and by turning on the logger you turn it on.

(3) will come in a separate PR - we will provide an API that gives access to the  historical details as usable by someone from the AdminSDK. There will likely be additions made to it when it manages to surface in the UI.

As a side note, there is a new form of message coming as part of the Slack/Teams integration work which is a diff based audit trail with more complete information that will be available and also includes fuller details. You may wish to take a look at the details being included and see if it is of interest. https://github.com/featurehub-io/featurehub/blob/main/backend/messaging-api/messaging-api.yaml

![image](https://github.com/featurehub-io/featurehub/assets/55768/d011a2ce-2f88-43e9-ad1d-5a73186b8ebe)

**Comment by amandam11** [comment]
Thanks for the updates, the planned changes sound great, and very useful.

**Comment by amandam11** [comment]
@rvowles I tested 1.6.2-RC for the changes you mentioned. The webhooks are getting the person id, and I can then look that person up using the admin-sdk.

However, I failed to get the feature-version history to work.

Scenario:
1. docker compose running party-server 1.6.1 with postgres database as per: 
2. Create features
3. Backed up the database
4. Stopped/removed the 1.6.1 featurehub/party-server
5. Updated docker compose to have featurehub/party-server:1.6.2-RC
6. Tried to get feature history - nothing back
7. Changed an existing feature - ok
8. Asked for feature history, nothing returned, and error in log e.g.
```
curl -H "Authorization: Bearer <token>" http://172.17.0.1:8085/mr-api/portfolio/48c2b04c-41dd-4299-9f6e-487a63ab7d27/application
[{"id":"94fcb3d4-d921-4945-8660-159567e0f119","name":"test","description":"test","portfolioId":"48c2b04c-41dd-4299-9f6e-487a63ab7d27","version":1,"groups":[],"features":[],"environments":[]}]

curl -H "Authorization: Bearer <token>" http://172.17.0.1:8085/mr-api/application/94fcb3d4-d921-4945-8660-159567e0f119/feature-history
```
and then in logs:
```
{"@timestamp":"2023-06-26T14:02:37.091+0000","message":"Failed jersey request","priority":"ERROR","path":"io.featurehub.jersey.config.LocalExceptionMapper","thread":"grizzly-http-server-27","stack_trace":"jakarta.ws.rs.NotFoundException: HTTP 404 Not Found\n\tio.featurehub.mr.resources.FeatureHistoryResource.listFeatureHistory(FeatureHistoryResource.kt:23) ~[mr-1.1-SNAPSHOT.jar:?]\n\tio.featurehub.mr.api.FeatureHistoryServiceDelegator.listFeatureHistory(FeatureHistoryServiceDelegator.java:44) ~[mr-api-java-server-1.1-SNAPSHOT.jar:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjava.lang.reflect.Method.invoke(Unknown Source) ~[?:?]\n\torg.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) [jersey-container-grizzly2-http-3.1.1.jar:?]\n\torg.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [grizzly-http-server-4.0.0.jar:4.0.0]\n\torg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [grizzly-framework-4.0.0.jar:4.0.0]\n\torg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [grizzly-framework-4.0.0.jar:4.0.0]\n\tjava.lang.Thread.run(Unknown Source) [?:?]","host":"featurehub","user":{"email":"8cb65eb8-d608-408f-9068-49a074553508@admin.sa.featurehub.io","id":"8cb65eb8-d608-408f-9068-49a074553508"}}
```

9. Created a new application, created a numeric feature, set feature value, and then tried to get feature-history on the new application. But still got the same response.
Used the application call to verify I'd got applicaiton correct:
```
$curl -H "Authorization: Bearer <token>" http://172.17.0.1:8085/mr-api/portfolio/48c2b04application/cdf517be-4c1a-4a48-a8cc-1f6a5a1d4eb4/feature-history
$ curl -H "Authorization: Bearer <token>" http://172.17.0.1:8085/mr-api/application/cdf517be-4c1a-4a48-a8cc-1f6a5a1d4eb4
{"id":"cdf517be-4c1a-4a48-a8cc-1f6a5a1d4eb4","name":"test2","description":"test2","portfolioId":"48c2b04c-41dd-4299-9f6e-487a63ab7d27","version":1,"groups":[],"features":[],"environments":[]}
```

**Comment by rvowles** [comment]
I think its a failure in my documentation :-) You must specify the feature keys or ids that you want, and unless you are a superuser, you must also specify the environmentIds. Its all optional because you have to specify keys or ids and depending on who you are, you may or may not need to specify environments. So I need to make the API docs more clear, sorry about that!

**Comment by amandam11** [comment]
@rvowles So I got it to work when I was a super-admin, and as a user whereby I explicitly set for the group they were in that they had access to the environment. But I'm having problems with portfolio admins, as its not working for them with the default settings.

By default the portfolio admins can change values, but if you look at the group permissions. Then the group doesn't have the boxes selected for access. However the portfolio admin can change those values.
![Default Settings](https://github.com/featurehub-io/featurehub/assets/112953605/cab156f7-80a5-4730-b3e0-e22f3e409dfd)


BUT if I try and access the feature-history for one of those environments, and use the token from an admin service account that has those rights (or the user's own token), then they get back 404. UNLESS I explicitly change the permissions for the portfolio admin group to have rights on have read rights on the relevant environment. Then after doing that it works.

Shouldn't portfolio admins be able to do the feature-history without having to explicitly grant them access to the environment (as they don't need that explicit permission in the UI to change the value)?

**Comment by rvowles** [comment]
Yes, you are absolutely right - its a side effect of portfolio admin's not having their per environment permissions explictly stored, so I better fix that!

**Comment by rvowles** [comment]
I actually merged and push this last night my time, so the 1.6.2-RC images should be updated...

**Comment by amandam11** [comment]
Thanks. I tried that and it now works for my portofolio admin.
