### ISSUE TITLE
Feature Request - Multiple API Keys for Key Rotations

### ISSUE THREAD

**Issue by jkim007** [featurehub-io/featurehub#1026]
**Is your feature request related to a problem? Please describe.**
In production systems there is a need for key rotations and currently Feature Hub only allows for a single API key to exist (for each application). This poses a problem as this creates downtime during the key rotation period.

**Describe the solution you'd like**
To remove the downtime necessitated during the key rotation period, it would be great if the following features existed:

1. Up to 2 API keys per application
2. Functionality to disable / remove one of the keys

**Describe alternatives you've considered**
Only alternative would be to deal with the downtime - which is not ideal.

**Additional context**

**Comment by rvowles** [comment]
Hey there!

API keys are associated with environments rather than applications and you can have as many as you like, you aren't restricted to one.

Hope that helps!

**Comment by jkim007** [comment]
@rvowles Oh, I see. So if I were to create a separate service account and give it access to the application, I would be able to do the rotation with no downtime?

**Comment by rvowles** [comment]
Yes! No problem!
