### ISSUE TITLE
Editing Groups for Admin Service Account has no affect

### ISSUE THREAD

**Issue by amandam11** [featurehub-io/featurehub#1031]
**Describe the bug**
If an admin service account is created with access to a particular portfolio/group in the UI, and then later on an edit is made to add an extra portfolio/group and saved then the edit has no affect.
When editing the account again the original settings are presented, and also using the keys then access to the additional portfolio is not permitted.

 Which area does this issue belong to?

* [ X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Have more than one portfolio
2. Create a admin service account and give it access to first portfolio, and hit Create
3. Edit the admin service account, and add a second portfolio, and hit Save and Close
4. Looking at the list of service accounts, it still shows only 1 group for the admin service account
5. If re-edit the admin service account, then only the original portfolio is shown
6. No errors are reported in the web console
7. Also if edit the admin service account, and change from one portfolio/group to another, hit Save/Close then on re-edit also get no change.

However, if we create a new service account and add 2 portfolio/group combinations on creation, then they are saved correctly.

No errors are reported in the admin console, and the HTTP  calls show:
1) HTTP PUT to http://localhost:8085/mr-api/person/b395f472-bca8-4f54-bcfd-5fbbbd1c766a/v2 with both groups in:
{"name":"testSA","version":1,"groups":["5f1d5d59-1623-431f-b90d-1e1f9c3c497d", "cf107924-d323-4258-9f1d-b3573b13c85d"]}
2) But when next ask for the service account on 2nd edit we see:
HTTP GET to http://localhost:8085/mr-api/person/b395f472-bca8-4f54-bcfd-5fbbbd1c766a?includeGroups=true
with response:
{
    "id": {
        "id": "b395f472-bca8-4f54-bcfd-5fbbbd1c766a"
    },
    "name": "TestSA",
    "email": "b395f472-bca8-4f54-bcfd-5fbbbd1c766a@admin.sa.featurehub.io",
    "personType": "serviceAccount",
    "version": 1,
    "passwordRequiresReset": false,
    "groups": [
        {
            "id": "5f1d5d59-1623-431f-b90d-1e1f9c3c497d",
            "admin": true,
            "portfolioId": "d72d9f4f-d90a-41c2-b7a1-cf6c33b4b594",
            "organizationId": "366295d1-d025-4213-b1fd-f85594a31824",
            "version": 1,
            "name": "Port1 Administrators",
            "members": [],
            "applicationRoles": [],
            "environmentRoles": []
        }
    ],
    "additional": []
}

Also if we try and use the service account key then we find it only has the permissions of the first group added.

**Expected behavior**
Editing the groups of an admin service account should change the groups it is in.

**Screenshots**

![SAIssue_Create](https://github.com/featurehub-io/featurehub/assets/112953605/03831e22-6faa-4e06-85da-83267e8216a2)

![SAIssue_Edit](https://github.com/featurehub-io/featurehub/assets/112953605/c68e1e2d-48d1-4053-b676-1f534068c0ad)
![SAIssue_ListAfterEdit](https://github.com/featurehub-io/featurehub/assets/112953605/2a4177a3-7709-4679-924d-08b46bbc213b)
![SAIssue_ReEdit](https://github.com/featurehub-io/featurehub/assets/112953605/f62eeba4-9867-4c76-ae25-6136c5d8d594)

**Versions**
 - FeatureHub version [e.g. 1.6.1 and 1.6.2-RC]
 - SDK version N/A
 - OS: Docker
 - Browser: Chrome

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**

**Comment by rvowles** [comment]
I've updated the 1.6.2-RC with the fix for this.

**Comment by amandam11** [comment]
Thanks @rvowles, I tested the new 1.6.2-RC and works perfectly now.

**Comment by rvowles** [comment]
We released 1.6.2 so you can use that instead of you like :-)
