### ISSUE TITLE
Trying to add a Rollout Strategy to a locked feature fails

### ISSUE THREAD

**Issue by robertmarsal** [featurehub-io/featurehub#1051]
**Describe the bug**
Using an `Admin Service Account` I am trying to use the API to add a Rollout Strategy to a feature that can be locked or not. The rollout strategies depend on a third party system. The issue I am seeing is if a feature is locked the API to update the rollout strategies still returns a 200 however the changes don't get applied. If I unlock the feature and try again everything works as expected.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [x] Other

**To Reproduce**
1. Lock a feature
2. Try to add a rollout strategy using the API `/mr-api/features/{eid}/feature/{key}`
3. See code 200 
4. Changes are not reflected in the UI

**Expected behavior**
Either an error is returned if this is the intended behaviour or the changes are applied since this is being actioned by an admin service account.

**Screenshots**

**Versions**
 - FeatureHub version 1.6.0

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**

**Comment by rvowles** [comment]
Hey there - yes, it should fail as it is locked. I will fix this 👍
