### ISSUE TITLE
Support GET API focused on Mobile

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub#109]
Mobile needs a GET API so it doesn't keep the radio open. Few Network operators have implemented the SSE handoff discussed in official documentation, so this periodic polling mechanism is worthwhile.

It needs to support multiple SDKURL requests in one, so it should be a simple GET /features

Ideally it should send something like: env=encoded-url,feature=version,feature=version&env=encoded-url,feature=version,feature=version so that the server can send back all the features it is missing (if any) and support multiple environments.

GET for caching.

**Comment by rvowles** [comment]
@chrusty do you think  given it wouldn't be cached anyway, we shouldn't turn it into a POST API then? I'm thinking for feature strategies this would allow the server to evaluate settings as well.

**Comment by chrusty** [comment]
@rvowles now that I have the background on this, I think the solution could be to have _two_ endpoints:

- GET /features could return the entire list of features including their strategies, and leave the interpretation up to the client
- POST /features would take a bunch of information in the request (client version, OS, random ID etc), and return a pre-interpreted list of features which the client would then blindly apply
