### ISSUE TITLE
Features count per page always resets back to default (5) after each addition of a new feature

### ISSUE THREAD

**Issue by mostafatalebi** [featurehub-io/featurehub#1105]
In the latest version of the FeatureHub, the pagination doesn't stay on the choice of the user. It always resets back to default (5 items). Here is the way to reproduce it:

1- Go to an application
2- Go to features to add a feature (we assume you have already several features there)
3- You set the count per page to 20, so you see all the features
4- You add the feature, and you see the page shows 5 features (the pagination defaults back to 5) (and the feature has been added successfully)

- While it is expected to show 20 features per page. And honestly it must have some global default around it.

**Comment by IrinaSouth** [comment]
Hi @mostafatalebi, thanks for reporting the issue. You are right, I managed to reproduce and have a fix ready to go. We will release 1.7.1 patch release for this once it's passed the builds etc.. https://github.com/featurehub-io/featurehub/pull/1106

**Comment by IrinaSouth** [comment]
this has been now released in 1.7.1 https://github.com/featurehub-io/featurehub/releases/tag/v1.7.1
