### ISSUE TITLE
WebHook URL can't be HTTPS

### ISSUE THREAD

**Issue by TheSylence** [featurehub-io/featurehub#1115]
**Describe the bug**
HTTPS Urls can't be used as Webhook URL because "Please enter a valid URL". 

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Go to Webhook Configuration
2. Enter `https://localhost` as Webhook URL
3. Validation fails with "Please enter a valid URL" and configuration can't be saved
4. `http://localhost` validates and can be saved

**Expected behavior**
HTTPS Urls can be used as a webhook URL.

**Versions**
 - FeatureHub version 1.7.2-RC

**Comment by IrinaSouth** [comment]
Hi there, 
Thanks for reporting this, we will add a fix for this asap.

**Comment by IrinaSouth** [comment]
Fix is released in 1.7.2-RC

**Comment by rvowles** [comment]
This was back-ported to the 1.7.1 current release - so those images have been refreshed with this fix.
