### ISSUE TITLE
Issues when upgrading to 1.7.0 -> 1.7.1

### ISSUE THREAD

**Issue by valodzka** [featurehub-io/featurehub#1117]
Evetying is the same as in #1090 (fixed 1.7.0 worked).

**Comment by rvowles** [comment]
we didn't cherry pick the fix over from  the 1.7.0 branch into the 1.7.1 branch - it should up updated on dockerhub in about 5 minutes.

**Comment by rvowles** [comment]
ok - its all pushed now. 1.7.2-RC uses main, so it brings in  the fix automatically.

**Comment by valodzka** [comment]
Thank you, can confirm that it works now
