### ISSUE TITLE
Setting service account permission for one application wipes off that in another account

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#1132]
**Describe the bug**

Assume scenario:

- a portfolio P1 with
- applications A1, A2, A3
- each (application) with environments E1, E2, E3
- service accounts S1, S2

Requirement:

- S1 needing following permissions across applications A1, A2, A3
- Read permission in environments E1, E2, E3
- S2 needing following permissions across applications A1, A2, A3
- Read permission in environments E1, E2, E3
- [Lock, Unlock, Change/Retire] permissions in E1

Problem:

- Setting above in one application wipes off setting in other applications
-- e.g., after setting above permissions in A1 (for S1), if the setting is repeated in A2 (for S1) then it wipes off earlier setting in A1 (for S1)

 Which area does this issue belong to?

* [/] FeatureHub Admin Web app
* [/] Admin SDK

**To Reproduce**
Repeat the steps provided above.

**Expected behavior**
For above scenario, service accounts S1 and S2 should be allowed to edit and set permission without affecting those for other applications.

**Comment by IrinaSouth** [comment]
hey @mik047 - cheers for reporting this. I have tested this scenario, you are right, there seem to be an issue with setting permissions for multiple apps using single Service Account. We are going to investigate and fix this, in the meantime workaround is to use single service account per application
