### ISSUE TITLE
Caching issue with Kinesis

### ISSUE THREAD

**Issue by rickybasra** [featurehub-io/featurehub#1149]
**Caching issue with Kinesis**
When using kinesis the edge endpoint does not reflect the any updates made to any of the features via the web UI. 

 Which area does this issue belong to?

* [X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Go to Admin Web app
2. Create a new feature e.g. simple boolean feature1
3. Use edge endpoint to get feature
4. Update feature
5. Check feature value using edge endpoint 

**Expected behavior**
Both the UI (MR) and edge endpoints should be giving the same data for a feature

**Screenshots**
Edge returns this
```
    "features": [
      {
        "id": "ce3b838e-b2bb-443d-af8b-87158f6e1263",
        "key": "rbtest",
        "l": false,
        "version": 18,
        "type": "BOOLEAN",
        "value": true,
        "strategies": []
      }
```
whilst mr endpoint (used by UI) returns this.
```
        {
            "id": "f3fff459-9342-44e3-a948-4165b22e223f",
            "key": "rbtest",
            "locked": false,
            "valueBoolean": false,
            "retired": false,
            "rolloutStrategyInstances": [],
            "rolloutStrategies": [],
            "environmentId": "0d18499f-3a6e-43eb-a725-af11b799073e",
            "version": 19,
            }
```
You'll see the version is out. If i uninstall and install the release edge picks up correct version.

**Versions**
 - FeatureHub version [e.g. 1.7.0]
 - Browser [e.g. chrome]

**Additional context**

**Comment by rvowles** [comment]
Kinesis has now been dropped, so closing this.
