### ISSUE TITLE
Dangerous character from history service URLs

### ISSUE THREAD

**Issue by petrosZavrakas** [featurehub-io/featurehub#1185]
**Describe the bug**
Hello,

We are facing the following issue. We are having a feature application with a payment system where we are using the jpmorgan SDK which is giving us the option to have PayPal as a payment option. This option is requiring to pass redirect and cancellation URLs. We are generating those URLs through the history-service and having the following format:

some-domain.com/?---={"featureappsection":"/subscription"}

The problem is that the curly brackets are getting handled as dangerous character:
the value must satisfy the following whitelist: alpha-numeric characters: “[A-Z]“, “[a-z]“, “[0-9]“; symbols: “.”, “:”, “+”, “/”, “?”, “@”, “&”, ” ' “, “-”, ” ” “, “_”, “=”, ” “, “(”, “)”.

From our understanding this issue will be affect not only our feature app but any feature app which is using the history service to generate urls which then will be used to payment system services like we do with the jpmorgan SDK.

Your support on the topic will be very much appreciated!

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [x] Other

**Versions**
@feature-hub/core: 2.13.0
@feature-hub/react: 2.13.0
@feature-hub/history-service: 2.13.0

**Additional context**

**Comment by rvowles** [comment]
This is a different project that has the same name as us.
