### ISSUE TITLE
STRATEGY: Support geographical rollout

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub#168]
Support geographical based rollout based on "country" attribute, enhanced with zones.

**Comment by rvowles** [comment]
Support for this based on country specific attribute matching is now in master, this ticket will now cover UI.

**Comment by rvowles** [comment]
awaiting suitable designs.

**Comment by rvowles** [comment]
The backend has been done for this and SDK rollout support is under PR. This ticket will stay open until the UI is complete.

**Comment by IrinaSouth** [comment]
Matchers logic: 

For country:  Equals, not equals - should send as a value. Includes, excludes - should send as an array
