### ISSUE TITLE
Auditing support

### ISSUE THREAD

**Issue by IrinaSouth** [featurehub-io/featurehub#204]
**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to see who updated and when the last feature value status, however it would be useful to have historical feature auditing support

**Comment by rvowles** [comment]
heya @cspalding - ebean supports a changelog output, so you can configure something like this if you want to get full db auditing: 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/55768/178616803-257381c9-295a-4bc8-9d0b-4c7529c1c7c8.png">

**Comment by rvowles** [comment]
We are putting feature value auditing into the next release, we will keep track of all changes to feature values in each environment, and we will have an API to extract that data along with a summary API for the UI. Do you have any other requirements?

**Comment by shaun-trusted** [comment]
Any update on this?

**Comment by rvowles** [comment]
We don't have a UI, but the APis are all there for this. Is that useful?
