### ISSUE TITLE
Copy SDK URL to Clipboard not working

### ISSUE THREAD

**Issue by eLoyyyyy** [featurehub-io/featurehub#280]
**Describe the bug**

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Go to the Admin Web app.
2. Select a service account.
3. Click on the "Copy SDK URL to clipboard" control.

**Expected behavior**
I should be able to copy the URL from that control.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 
 - Version 85.0

**Additional context**
Whenever I click on the icon, an error pops up. And whenever I check my clipboard, there's nothing being copied.
![Screenshot from 2021-02-02 10-51-04](https://user-images.githubusercontent.com/19218300/106545586-a1b35c80-6544-11eb-8aa2-b6e4e147852a.png)

I'm still on the process of integrating this into a sample project as research so we can improve our current workflow. Also I can see the SDK URL on the logs of the demo container so I can still continue. Props for creating this project!

**Comment by rvowles** [comment]
It only works against localhost or on https, those are the permissions of the browser. Are you using it against those?

**Comment by eLoyyyyy** [comment]
yes, both localhost (demo container) and the demo link has the same behavior.

**Comment by rvowles** [comment]
@eLoyyyyy so you run against demo.featurehub.io and you get the same problem?

**Comment by eLoyyyyy** [comment]
> @eLoyyyyy so you run against demo.featurehub.io and you get the same problem?

yes, same error seen on Chrome Dev Tool console. same behavior that there's nothing being copied on clipboard. On both demo.featurehub.io and on demo container (featurehub/party-server:1.1.1). I'm currently trying to do https on localhost to see if I still get the same behavior. I would assume it's still the same because of the behavior on demo.featurehub.io.

**Comment by IrinaSouth** [comment]
hi @eLoyyyyy. I managed to reproduce this in Firefox and I have the fix which should be merged soon. https://github.com/featurehub-io/featurehub/pull/281 
Then we will push new Docker version with this fix.  Thank you for reporting this!

**Comment by IrinaSouth** [comment]
fixed and released in version 1.1.2
