### ISSUE TITLE
SDK Java-Jersey 1.3 missing classes

### ISSUE THREAD

**Issue by fastboyz** [featurehub-io/featurehub#321]
**Describe the bug**
The Java Jersey example makes uses of these classes, 

import io.featurehub.client.FeatureRepositoryContext;
import io.featurehub.client.EdgeService;

but they are not available in the SDK.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [x] SDK
* [x] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1.Create a Java maven project
2. Add the following dependencies
```
 <dependency>
            <groupId>io.featurehub.sdk</groupId>
            <artifactId>java-client-jersey</artifactId>
            <version>[2, 3)</version>
        </dependency>
        <dependency>
            <groupId>io.featurehub.composites</groupId>
            <artifactId>composite-jackson</artifactId>
            <version>1.2</version>
        </dependency>
        <dependency>
            <groupId>io.featurehub.composites</groupId>
            <artifactId>composite-jersey</artifactId>
            <version>1.2</version>
        </dependency>
```
3.Try to import one of the mentioned class
4. See as they are not found

**Expected behavior**
The classes should she found and able to be imported
![screenshot](https://user-images.githubusercontent.com/11761430/114488799-fd9eff00-9bdf-11eb-95a3-a76652ac2782.PNG)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 87.0

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**
You can find the code here https://github.com/fastboyz/featureHubQuarkusIntegration/pull/new/featurehub/bug

**Comment by rvowles** [comment]
Did you build this yourself? There is no released version of the jersey 2.X client, its on a branch?

**Comment by rvowles** [comment]
The current released version of the jersey client is 1.2, so unless you have built and installed this yourself I'm not sure how you are getting these classes?

**Comment by fastboyz** [comment]
I am using the version 1.2 of the client 
```
<dependency>
            <groupId>io.featurehub.sdk</groupId>
            <artifactId>java-client-jersey</artifactId>
            <version>1.2</version>
        </dependency>
```

**Comment by rvowles** [comment]
Nice to see such enthusiasm! If you want to use the branch it's the main one in the PR. Your feed back would if course be appreciated and I can do a custom docker image for you.

**Comment by fastboyz** [comment]
Will definitely take a look at it! The docker Image would be great too!
