### ISSUE TITLE
Adding remote configuration as a separate Entity in the platform

### ISSUE THREAD

**Issue by pateash** [featurehub-io/featurehub#323]
**Is your feature request related to a problem? Please describe.**
Currently, the Remote configuration is ensembled with the Features, but there might a use case where user only wants to use remote configuration.

**Describe the solution you'd like**
In the platform apart from Features, User should be able to create remote configuration, which could be boolean, string , number or List of above types.

**Describe alternatives you've considered**
I have seen a solution in one of the Firm I worked, I would like to see same feature in open-source world.

**Comment by rvowles** [comment]
Could you be a little more detailed on what you are suggesting here? A "feature" is just a named thing with a type and a value. You can just use this as remote config in an app if you like.

**Comment by IrinaSouth** [comment]
Hi @ashishpatel0720 , just to add to @rvowles comment, it means that all feature types that FeatureHub platform offers - `boolean (feature flag), string, number, json` operate in exact same way, so if you want to use boolean with your remote configuration, you can just create a new feature of type boolean (we named it Feature Flag in our Admin UI app).

https://docs.featurehub.io/#_features

<img width="784" alt="Screenshot 2021-04-16 at 09 48 07" src="https://user-images.githubusercontent.com/9538697/114942582-daeb3f80-9e98-11eb-8edf-9780c107d442.png">
