### ISSUE TITLE
Java Client SDK for jdk 1.8

### ISSUE THREAD

**Issue by vinothank95** [featurehub-io/featurehub#328]
Is java SDK support jdk 1.8?
 we are using jdk 1.8 for our project. Is it possible to compile client sdk with jdk 1.8?

**Comment by rvowles** [comment]
It is compiled with JDK 1.8 to support Android.

**Comment by rvowles** [comment]
Let me correct that - the EventSource jersey client is compiled with Java 11. The core and android clients (and their dependent libraries) are all Java 8.
