### ISSUE TITLE
Party server image config  root issues

### ISSUE THREAD

**Issue by fastboyz** [featurehub-io/featurehub#409]
**Describe the bug**
Containers that do not allow to run commands in have a hard time running the pary-server as a standalone.

 Which area does this issue belong to?

* [ ] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [x] Other

**To Reproduce**
1. Have the a policy on K8s or Openshift that does not allow for root in pods
2. Try running the fh/party-server
3. Notice None of the nginx process are starting 

**Expected behavior**
The pods runs normally and the application is available.

**Screenshots**

**Desktop (please complete the following information):**

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**
This is cause by the fact that the pod cannot run as root, therefore, Nginx is not able to create  some folders it needs, namely :
* `/var/lib/nginx/body`
* `/var/lib/nginx/proxy`
* 
of top of that, www-data should be the owner of those folders plus:
* `/var/lib/nginx`
* ` /var/log/nginx`
* `/usr/share/nginx`

Finally, Nginx cannot bind the the port 80 without root.

**Comment by rvowles** [comment]
Thanks for logging this @fastboyz - it ended up being quite the thing to work out eh? So in the end it was simply changing permissions and making the nginx run on a different port? I know we tried a few things - like not having it buffer to disk and a few other things?

**Comment by fastboyz** [comment]
Yes It was mainly those, but I also change permissions on some folders to 777, but I am sure pre-creating the folders, changing the owners, and finally changing the port from 80 to 8080.

**Comment by rvowles** [comment]
I've started work on this, I have the Party Server sorted but I need to split nginx from MR in the split containers.
