### ISSUE TITLE
Provide alternative SSE client for Java

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub#416]
For those that don't want to use Jersey 2, there is currently no alternative. Provide an alternative using OKHttp3 SSE's library.

**Comment by rvowles** [comment]
refers to discussion: https://github.com/featurehub-io/featurehub/discussions/410

**Comment by rvowles** [comment]
@pontamilselvan are you by any chance able to build this branch? You would need to build and install everything unfortunately, but that is:

cd backend
mvn -f pom-first.xml clean install
cd ..
mvn -T4C clean install

You can then depend on:
  <groupId>io.featurehub.sdk</groupId>
  <artifactId>java-client-sse</artifactId>
  <version>1.1-SNAPSHOT</version>
instead of the jersey client and it should connect for you.

**Comment by pontamilselvan** [comment]
So instead of jersey client... i can use java-client-sse jar to connect?

**Comment by rvowles** [comment]
You could have yes :-) I needed someone to test it. If you are using jersey 2 now you may as well stick with Jersey!
