### ISSUE TITLE
[Admin UI] Registration URL doesn't work (only local debugging mode)

### ISSUE THREAD

**Issue by IrinaSouth** [featurehub-io/featurehub#430]
**Describe the bug**
This happens on fresh browsers (e.g. incognito mode).  In debug mode it results in an error: 

![Screenshot 2021-06-06 at 18 33 42](https://user-images.githubusercontent.com/9538697/120915047-ba4fa100-c6f5-11eb-8485-62fa0cc917b3.png)

However while debugging, the issue seem to relate to shared prefs: 

`The following LateError was thrown building IconTheme(color: Color(0xff473e8f), opacity: 1.0, size:\\n24.0):\\nLateInitializationError: Field '_sharedPreferences' has not been initialized.\\n\\nThe relevant error-causing widget was:\\n  MaterialApp file:///Users/irina/featurehub-io/admin-frontend/app_singleapp/lib/main.dart:50:18\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 187:26  DartError\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:28  throw_\\npackages/app_singleapp/api/client_api.dart 122:24                             swapRoutes\\npackages/app_singleapp/api/router.dart 100:14                                 navigateTo\\npackages/app_singleapp/main.dart 63:20                                        <fn>\\npackages/flutter/src/widgets/navigator.dart 4155:30                           <fn>\\npackages/flutter/src/widgets/navigator.dart 2814:31                           defaultGenerateInitialRoutes\\npackages/flutter/src/widgets/navigator.dart 3439:41                           restoreState\\npackages/flutter/src/widgets/restoration.dart 984:5                           <fn>\\npackages/flutter/src/widgets/restoration.dart 970:7                           didChangeDependencies\\npackages/flutter/src/widgets/navigator.dart 3485:11                           didChangeDependencies\\npackages/flutter/src/widgets/framework.dart 4732:11                           <fn>\\npackages/flutter/src/widgets/framework.dart `

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app

**To Reproduce**
1. Go to Register a new user screen
2. Click on copy registration URL
3. Open "Incognito" browser and insert the URL

**Comment by rvowles** [comment]
This is only for when you are developing in the IDE and it appears to be a Flutter Development issue.

**Comment by rvowles** [comment]
This was resolved by the move to the new Navigator. Tested and works.
