### ISSUE TITLE
Java Script SDK not working in Release mode for React Native

### ISSUE THREAD

**Issue by krunaldarji** [featurehub-io/featurehub#456]
FeatureHub javascript SDK works fine in debug mode but once i turn off debug mode FeatureHub configuration listener giving NotReady error.

**Comment by IrinaSouth** [comment]
Hi there, could you please provide some more details, ideally a code snippet and confirm which SDK version you are using. Cheers

**Comment by krunaldarji** [comment]
Thanks for your reply @IrinaSouth 

we are using featurehub-javascript-client-sdk - 1.0.4 in React Native Project

**Comment by IrinaSouth** [comment]
Thanks for providing the details. By default this SDK will use SSE client, however with React Native it is recommended to use polling client, you can override it like this just after your fhConfig initialisation:

```
import { FeatureHubPollingClient } from 'featurehub-javascript-client-sdk';
const FREQUENCY = 5000; // 5 seconds
fhConfig.edgeServiceProvider((repo, config) => new FeatureHubPollingClient(repo, config, FREQUENCY));
```
in this case it is configured for requesting an update every 5 seconds.


This is also explained in the SDK readme https://www.npmjs.com/package/featurehub-javascript-client-sdk

**Comment by krunalsperidian** [comment]
Thanks again @IrinaSouth  i will keep you posted!

**Comment by krunalsperidian** [comment]
@IrinaSouth  we can close this issue above solution worked on React Native release version

**Comment by IrinaSouth** [comment]
Awesome @krunalsperidian! Let me know if anything else comes up. Thanks

**Comment by NamrataDwivedi** [comment]
Getting 504,
Request URL: https://featurehub.pocketcfoapp.com/mr-api/initialize
Request Method: GET
Status Code: 504

**Comment by IrinaSouth** [comment]
Hi @NamrataDwivedi - could you please open a new issue as this one is closed and provide the details. Thank you.

**Comment by NamrataDwivedi** [comment]
https://github.com/featurehub-io/featurehub/issues/461
