### ISSUE TITLE
The initialize api of feature hub is giving 504 after putting app in App Store

### ISSUE THREAD

**Issue by NamrataDwivedi** [featurehub-io/featurehub#461]
**Describe the bug**
Getting 504 in the initialize api,
Request URL:
https://featurehub.app.com/mr-api/initialize
Request Method:
GET
Status Code:
504

 Which area does this issue belong to?

* [x] SDK

**To Reproduce**
1. Upload the app on App Store.
2. After sometime it stops working and started giving 504.

**Expected behavior**
It should work even after the upload on App Store. 

**Screenshot**
 @[](url)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/19549471/125264332-64d46880-e321-11eb-8207-ccb04f0ab867.png)

**Additional context**
```
import {
  EdgeFeatureHubConfig,
  Readyness,
  FeatureHubPollingClient
} from "featurehub-javascript-client-sdk";

const edgeUrl = "https://featurehub.app.com/features/";
const apiKey =
  "default/o00000g4-2745-43b3-b4d8-39f0138f3a3e/Rg5Fdl2jbr5IX4YkjzPR*Bf2SBweY6HBPz959uhc";
const fhConfig = new EdgeFeatureHubConfig(edgeUrl, apiKey);

const FREQUENCY = 5000;

fhConfig.edgeServiceProvider((repo, config) => new FeatureHubPollingClient(repo, config, FREQUENCY));
let initialized = false;
    fhConfig.addReadynessListener(async (ready) => {
      console.log("at start feature 1");
      if (!initialized) {
        if ((ready = Readyness.Ready)) {
          initialized = true;
          const fhClient = await fhConfig.newContext().build();
      }
    }
```

**Comment by IrinaSouth** [comment]
Hi @NamrataDwivedi. Thanks for reporting the issue. The error indicated that something is not right with the hosting/deployment of your FeatureHub Admin app, and I don't think it's anything to do with your App Store app. Which database did you use for the FeatureHub deployment? Is it Postgres or MySql? How many servers with the FeatureHub instance are you running?

**Comment by NamrataDwivedi** [comment]
Hi @IrinaSouth,

As of now we are not using any database and FeatureHub is running only on 1 server.

**Comment by IrinaSouth** [comment]
Sounds like you must be running Option1 as described here? https://docs.featurehub.io/installation.html ?    If so, there are limitations to this option and as described in the docs, we only recommend this option for evaluation deployments, but not for production. It is possible that when your mobile app started hitting the FeatureHub server it ran out of memory.
If you are able to see the logs from the FeatureHub server, this would be one way of confirming what exactly caused the error. You could paste it here and we can investigate further. However please check that you running FeatureHub server suitable for production loads. Cheers.

**Comment by NamrataDwivedi** [comment]
Thank @IrinaSouth  I will check this and keep you posted.

**Comment by rvowles** [comment]
@NamrataDwivedi I think this is to do with #465 - I was making updates to it and I have discovered a scenario where the polling SDK client for js will end up sending endless requests to the server probably bringing it down. It will be fixed with the next release which is pending review.

**Comment by IrinaSouth** [comment]
Hi @NamrataDwivedi - is it all good for you now?
