### ISSUE TITLE
Featurehub installation with Option 2

### ISSUE THREAD

**Issue by NamrataDwivedi** [featurehub-io/featurehub#477]
**Describe the bug**
As described in the https://github.com/featurehub-io/featurehub/issues/465, we installed the featurehub with option 2,
https://docs.featurehub.io/installation.html.

Current installed version is 1.2.0.

The setup page works fine but when added the client key to the url eg : features/default/... it gives 404. 

 Which area does this issue belong to?

* [x] SDK
* [x] Documentation

**To Reproduce**
1. Followed the Option 2 from https://docs.featurehub.io/installation.html.
2. Append the client key.
3. Page gives 404.

**Expected behavior**
It should give 200 and show responses with the features added.

**Screenshots**
![Screenshot 2021-07-28 at 4 44 58 PM](https://user-images.githubusercontent.com/19549471/127313599-52adf801-78ac-4c68-a07e-6de5570aeb94.png)
![Screenshot 2021-07-28 at 4 44 23 PM](https://user-images.githubusercontent.com/19549471/127313611-72adbf40-4318-44c7-ae98-e893dd1f5924.png)

**Desktop (please complete the following information):**
OS : Ubutnu
Version : 18.04.3
Docker version : 19.03.12
docker-compose version is 1.27.0

**Comment by rvowles** [comment]
Hi Namrata - for Option 2, we don't provide an nginx proxy server, so I suspect that may be what is missing? It is expected you would have two load balancers - one which directs traffic to your MR server (like you have already) and another which directs traffic to the Edge container which is running on port 8553. 

You can if you wish build a container that directs traffic to both of them if you wish? If you pull the party-server container and start it up, you can docker exec into it, change to the /etc/nginx/sites-enabled folder and you can grab the config out of there which would do what you want?

We should add this to the documentation and add a basic container that does this for you.

**Comment by NamrataDwivedi** [comment]
Ok, I will inform my team for it. Will keep you posted.

**Comment by NamrataDwivedi** [comment]
Hi @rvowles ,

Below is our ngix configuration :

root@8a30d1af2cff:/etc/nginx/sites-enabled# cat default
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
        # management repository is here
        location /mr-api/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://localhost:8903/mr-api/;
        }
        location /oauth/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://localhost:8903/oauth/;
        }

 

        # prometheus
        location /metrics {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://localhost:8903/metrics;
        }
        location /health {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://localhost:8903/health;
        }
}

This is the nginx config file under the MR latest container.

Do I need to add anything here ?

Let me know if you need more details.

**Comment by rvowles** [comment]
Hi there, you will need to add the following:

` # sse-cache is loaded here
        location /features/ {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://DBHOST:8553/features/;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
        }

        # this is required just for OPTIONS as the above works for GET
        location /features {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://DBHOST:8553/features;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
        }`

If you are using docker-compose on the same machine, the DBHOST is probably called "edge" - its in the same docker-compose file here:

`edge:
    image: featurehub/edge:latest
    restart: always
    user: 999:999
    volumes:
      - ./edge-config:/etc/app-config
      - ./common-config:/etc/common-config
    ports:
      - 8553:8553
    depends_on:
      - "nats"`

The name in the docker-compose becomes the hostname by default. Hope this helps!

**Comment by NamrataDwivedi** [comment]
Thank you @rvowles. I will just add this and give you the feedback.

**Comment by NamrataDwivedi** [comment]
HI @rvowles , Thank you for your help. It is working now.
