### ISSUE TITLE
Featurehub setup everytime when container restarts

### ISSUE THREAD

**Issue by luchees** [featurehub-io/featurehub#482]
**Describe the bug**

I'm using a one in all setup with an external postgres db.
I can setup my account, create a feature flag and implement with sdk.
After container restarts the setup needs to be done again and my flags are gone.
I'm a bit lost as I thought the config will be saved in the database. 
Do I also need persistent storage for some container?

 **Which area does this issue belong to?**

- [x] * FeatureHub Admin Web app
- [x] * Documentation

**To Reproduce**
1. Steps to reproduce the behavior:
2. Setup fargate service in AWS with correct env vars and featurehub image.
3. Expose port 8085
4. setup loadbalancer and targetgroup with healthchecks
5. setup featurehub on loadbalancer url
6. restart container
7. go to loadbalancer url again and see that you need to do the setup again

**Expected behavior**
after restarting the container you should not be redirected to the setup again

**Additional context**

[logs.txt](https://github.com/featurehub-io/featurehub/files/6942421/logs.txt)

**Comment by IrinaSouth** [comment]
Hi @luchees, cheers for reporting the issue with all the details. 

Could you please confirm how you are configuring the container to talk to the external Postgres db?

And to your question about persistent storage - this shouldn't be required. 

Cheers, 
Irina

**Comment by luchees** [comment]
Hi @IrinaSouth 

 I now see in the logs that it's using H2 database. 

I've setup a Fargate service so it's not easy for me to setup with the application.properties file.
So I've setup this with Env vars.
        DB_USERNAME: 'featurehub',
        DB_URL: `jdbc:postgres://${dbEndpoint}:${dbPort}/${dbName}`,
        NATS_URLS: 'nats://localhost:4222',
        REGISTER_URL: `${loadBalancerDnsName}/register-url?token=%s`,
        DB_PASSWORD: ecs.Secret.fromSecretsManager(props.dbSecret),

 Maybe reask my question:

 **How can I use env vars in featurehub instead of the application.properties file?**

**Comment by luchees** [comment]
Thank you @rvowles for the fix. Will make use of 1.4.1 as soon as it's released.

**Comment by IrinaSouth** [comment]
associated commit in the dependency https://github.com/ClearPointNZ/connect-java/commit/b0ce7c37fc44f832c3e4fef0a91800fc2c17ed3a

**Comment by IrinaSouth** [comment]
This has been released in 1.4.1

**Comment by IrinaSouth** [comment]
There is also a relevant PR with docs updates in the [featurehub-install repository ](https://github.com/featurehub-io/featurehub-install/pull/15/files)
