### ISSUE TITLE
Support for static flag eval.

### ISSUE THREAD

**Issue by igorgatis** [featurehub-io/featurehub#497]
**Is your feature request related to a problem? Please describe.**
The goal is to achieve massive scalability. Consider a heavily accessed website which is generated using a Static Site Generator (such as Gatsby or Next.js) and it gets served through a CDN for latency and scalability reasons. I can't use FeatureHub as is because both Server Side and Client Side Eval will cost a lot or won't scale.

**Describe the solution you'd like**
Ideally, feature information (the one used by Client Side Eval) should be fetched during build time and stored as part of the website. For instance, with Gatsby, it could be stored as a json file or even hardcoded inside the javascript source. This way, the browser won't need to fetch from the edge service (in fact, edge service is only required during build time). Whenever feature data changes, site owner can rebuild the website and publish it.

Here is a sample usage snippet in Typescript:
```typescript
// FEATURES_ENVIRONMENT gets populated during build time.
const fhClient = new StaticClientContext(FEATURES_ENVIRONMENT).userKey(user).build();
```

**Describe alternatives you've considered**
Considered both Client Side and Server Side Evals but they both will require massive infrastructure.

**Additional context**
Actually, this functionality is almost available. Here is a sample code implementation:

```typescript
class StaticClientContext extends BaseClientContext {
  constructor(environment: Environment) {
    super(new ClientFeatureRepository(), new DummyFeatureHubConfig());
    this._repository.notify(SSEResultState.Features, environment.features);
  }

  async build(): Promise<ClientContext> {
    return this;
  }

  feature(name: string): FeatureStateHolder {
    return this._repository.feature(name).withContext(this);
  }

  edgeService(): EdgeService {
    return new DummyEdgeService();
  }

  close() {}
}
```

Notice that I had to implement `DummyEdgeService` and `DummyFeatureHubConfig` just to satisfy `BaseClientContext`'s requirements. In fact, the following changes to `BaseClientContext` should be harmless:
```patch
export abstract class BaseClientContext implements ClientContext {
-  protected readonly _config: FeatureHubConfig;
 
-  protected constructor(repository: InternalFeatureRepository, config: FeatureHubConfig) {
+  protected constructor(repository: InternalFeatureRepository) {
     this._repository = repository;
-    this._config = config;
   }
 
-  abstract edgeService(): EdgeService;
   abstract close();
 ```

**Comment by rvowles** [comment]
This is a neat idea! I think it would, for a full DevOps culture style of approach need to be associated with WebHooks into your CI, but making these changes into the code base would be a great first start. Did you want to do a PR or leave it with us?

**Comment by igorgatis** [comment]
Here is the PR that simplifies `BaseClientContext` #502. It is just a suggestion.

**Comment by rvowles** [comment]
Looks good to me! Merged!

**Comment by igorgatis** [comment]
Sorry, left some unneeded of imports, #503 fixes that.

**Comment by igorgatis** [comment]
For future reference: although it might be convenient to use a JSON to serve feature strategies and use `fromJson` to parse it, it makes much more sense to use javascript as if one had hardcoded the data as part of the source code. This should yield better performance as it uses native javascript parser. Besides, it opens an opportunity to shrink bundle size even further by not including `model_serializer.js` which alone represents almost 30% of total packed size.

![image](https://user-images.githubusercontent.com/1269388/130714367-d80ccc34-7aa4-4190-9dfc-8ba400754db6.png)

**Comment by IrinaSouth** [comment]
This is now released in v. 1.0.7 for both client and node javascript SDKs. Massive thanks to @igorgatis for the idea and contribution.  :)

**Comment by igorgatis** [comment]
related: https://github.com/webpack/webpack/tree/main/examples/side-effects
