### ISSUE TITLE
Javascript SDK - consider removing `model_serializer.ts` in favor JSON parse/stringify

### ISSUE THREAD

**Issue by igorgatis** [featurehub-io/featurehub#519]
The `node_serializer.ts` occupies a significant portion of overall JavaScript SDK package. It sounds like it could be replaced entirely by `JSON.parse` and `JSON.stringify`.

**Describe the solution you'd like**
Replace  content of `toJson` and `fromJson` with `JSON.xxxx` calls. Or remove `node_serializer.ts` entirely.

**Describe alternatives you've considered**
I successfully experimented with `JSON.parse`. further testing is required for sure.

**Comment by rvowles** [comment]
The entire set of code for that is generated using openapi - so its something I am looking at. Its important we don't hand craft it, but I don't think I do instance checks anywhere so it _should_ be ok to replace it with JSON.parse

**Comment by igorgatis** [comment]
That's what I thought. I'm concerned mostly about `null`, `undefined` and `[]` values. We can always review code entirely to make sure these are //handled in the same way// or we can convert these down to `undefined` using some generic recursive traversal.

Thia issue is mostly to document this discussion and figure whether it makes sense.

**Comment by rvowles** [comment]
I added testing around it - because of the way classes are  constructed with partials I am now doing instanceof checks as data comes in and just newing them if they aren't FeatureStates. I have written an extra test to use raw json data and it seems to work ok. Will put this in for the next release.
