### ISSUE TITLE
Adding attribute_value to the context doesn't always enabled

### ISSUE THREAD

**Issue by AmiraNagi** [featurehub-io/featurehub#520]
Using featuerhub admin UI, we added a custom rule with name "companyName", we made the feature flag default to "Off" , we made the feature "On" for the custom rule strategy, 
the feature is not consistently enabled.

**Which area does this issue belong to?**
we use "featurehub-javascript-client-sdk": "^1.0.8"
featurehub/party-server:1.3.3
macOS
chrome - firefox

```
private featureMap: {
  [key: string]: BehaviorSubject<boolean>
} = {}

public isEnabled(feature: string, companyName): Observable<boolean> {
    if (!(feature in this.featureMap)) {
      this.featureMap[feature] = new BehaviorSubject(false)
      this.callFeatureHub(feature, companyName)
    }
    return this.featureMap[feature]
  }

  private async callFeatureHub(feature: string, companyName) {
    let initialized = false
    const fhConfig = new EdgeFeatureHubConfig(
      environment.featurehubUrl,
      environment.featurehubApiKey
    ).init()
    let failCounter = 0
    console.log("companyName from cookie " + companyName);
    const fhClient = await fhConfig.newContext().attribute_value('companyName', companyName).build()
    fhConfig.addReadynessListener(async (ready) => {
      console.log("readyness listener state " + ready + " for feature " + feature);
      if (!initialized && ready == Readyness.Ready) {
        console.log("fhClient.isEnabled(feature)  " + fhClient.isEnabled(feature) + " for feature " + feature);
        this.featureMap[feature].next(fhClient.isEnabled(feature))
        initialized = true
      } else if (ready === Readyness.Failed && failCounter > 3) {
        fhConfig.close()
        initialized = false
      } else if (ready === Readyness.Failed) {
        failCounter++
        this.featureMap[feature].next(false)
      } else {
        failCounter = 0
      }
    })
  }
```
then we call isEnabled to route to different paths
```
this.featurehubService
                  .isEnabled('NEW_FEATURE', "companyName")
                  .pipe(
                    skip(1) // skip first response because it's not ready
                  )
                  .subscribe(isSet => {
                    console.log('NEW_FEATURE ' + isSet)
                    if (isSet) {
                      this.router.navigate(['service', 'v2']);
                    } else {
                      this.router.navigate(['service', 'v1'])
                    }
                  }) 
```

**Expected behavior**
the feature is always enabled as long as "companyName" rule is "On"

**Actual**
the feature sometimes returns as isEnabled = false and sometimes returns isEnabled = true correctly.

**Comment by rvowles** [comment]
Hi there! Thanks for logging the question.

So just first up - you appear to be creating a new connection to the repository for every feature, is that intended? Normally you would just create a single connection. 

Could you please include the console logs that are coming from the server, and could you please also put a console log in the fail checking? that would let us see in what order things and data are coming from your FH server!

Thanks! And we look forward to helping you further.

**Comment by AmiraNagi** [comment]
Hello, Thanks for the quick response.
Thanks for bringing that point up, I tried to move the connection up to get it created once, in the single feature code it worked as expected, however when we use nested features it gets stuck at some point. 

```
this.featurehubService
        .isEnabled('FEATURE_ONE')
        .pipe(
          skip(1) // skip first response in case feature not yet in map
        )
        .subscribe(featureOne => {
          console.log('featureOne ' + featureOne)
          if (featureOne) {
            console.log('featureOne is on')
            this.router.navigate(['f1'])
          } else {
                this.featurehubService
                  .isEnabled('FEATURE_TWO', 'testone')
                  .pipe(
                    skip(1) // skip first response in case feature not yet in map
                  )
                  .subscribe(isSet => {
                    console.log('FEATURE_TWO ' + isSet)
                    if (isSet) {
                      this.router.navigate(['service', 'v2']);
                    } else {
                      this.router.navigate(['service', 'v1'])
                    }
                  })
          }
        })
```
featurehubService now looks like

```
  private featureMap: {
    [key: string]: BehaviorSubject<boolean>
  } = {}

  fhConfig = new EdgeFeatureHubConfig(
    environment.featurehubUrl,
    environment.featurehubApiKey
  ) // also tried adding .init() here but same issue

public isEnabled(feature: string, companyName?): Observable<boolean> {
    if (!(feature in this.featureMap)) {
      this.featureMap[feature] = new BehaviorSubject(false)
      this.callFeatureHub(feature, companyName)
    }
    return this.featureMap[feature]
  }

  private async callFeatureHub(feature: string, companyName?) {
    let initialized = false
    let failCounter = 0
    console.log("companyName is " + companyName);
    const fhClient = await this.fhConfig.newContext().attribute_value('companyName', companyName).build()
    this.fhConfig.addReadynessListener(async (ready) => {
      console.log("readyness listener state " + ready + " for feature " + feature);
      if (!initialized && ready == Readyness.Ready) {
        console.log("fhClient.isEnabled(feature)  " + fhClient.isEnabled(feature) + " for feature " + feature);
        this.featureMap[feature].next(fhClient.isEnabled(feature))
        initialized = true
      } else if (ready === Readyness.Failed && failCounter > 3) {
        this.fhConfig.close()
        initialized = false
      } else if (ready === Readyness.Failed) {
        failCounter++
        this.featureMap[feature].next(false)
      } else {
        failCounter = 0
      }
    })
  }
```

console logs

```
>> companyName is undefined
>> readyness listener state NotReady for feature FEATURE_ONE
>> readyness listener state Ready for feature FEATURE_ONE
>> fhClient.isEnabled(feature)  false for feature FEATURE_ONE
>> featureOne false
>> companyName is testone
>> readyness listener state NotReady for feature FEATURE_ONE
>> readyness listener state NotReady for feature FEATURE_TWO
```
then bunch of errors from
```
GET {featurehubURl}?xfeaturehub=companyName= net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
GET {featurehubURl}?xfeaturehub=companyName=testone net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 
```

with the previous code when the connection was created each time the console logs were

```
>> companyName is undefined
>> readyness listener state NotReady for feature FEATURE_ONE
>> readyness listener state Ready for feature FEATURE_ONE
>> fhClient.isEnabled(feature)  false for feature FEATURE_ONE
>> featureOne false
>> companyName is testone
>> readyness listener state NotReady for feature FEATURE_TWO
>> readyness listener state Ready for feature FEATURE_TWO
>> fhClient.isEnabled(feature)  false for feature FEATURE_TWO
>> FEATURE_TWO false
```
while FEATURE_TWO should be true

**Comment by rvowles** [comment]
Ok, thanks for the logs! That was very useful! So you are using the SSE client from the browser with a Server Evaluated Key. That should definitely work, and I think to support it, your first choice of how you coded it is the better choice - where you are holding open one connection for each feature, and having a separate repository for each feature, especially as you are changing the context differently for each feature. This type of technique is more like a batch job and it should definitely work.

I have used our sample database we use for our testing and I added an option with the custom field and a companyName with "testone" and confirmed that with the xfeaturehub= parameter set as you are showing, it is correctly returning the right data - so  the server is doing the right thing, so it must be some bug in our SDK thats making it act strangely and I'd like to nail this - its an important use case. 

As I don't have a ready example with the code you are using - is there a chance you could create a cut down example with just this in it and the basic code for me? It would help enormously to solve it and let us get it resolved quickly?

**Comment by AmiraNagi** [comment]
Hi Richard, thanks for your investigations, I added here a simple code that reproduce the issue
https://github.com/AmiraNagi/featurehub-example 
please modify it with your featurehub url and apiKey, 
then create a feature flag in featurehub UI , called "FEATURE_TWO" 
then add a custom rule strategy that has "testone" String value, 
and after running `npm install` and `npm start` you can access `http://localhost:4200/company` and check console logs 
it should be `>> navigate to v2` but if you keep refreshing the page you'll notice sometimes `>> navigate to v1`

**Comment by rvowles** [comment]
Hiya! Thanks for this, much much appreciated! I figured it out, so this section:

const fhConfig = new EdgeFeatureHubConfig(
      environment.featurehubUrl,
      environment.featurehubApiKey
    ).init()

What is happening here is that the .init() is only supposed to be used for client side evaluation, it doesn't really work for server side evaluation. What is happening is it is like doing this:

const fhConfig = new EdgeFeatureHubConfig(
      environment.featurehubUrl,
      environment.featurehubApiKey
    )
fhConfig.newContext().build()
const fhClient = await fhConfig.newContext().attribute_value('companyName', companyName).build()

So what is happening occasionally is that the first connection with no context is returning _after_ the second context (its just javascript right?) and therefore coming back with features as if you didn't specify a company name. 

If you remove the .init() you should be good! Once I did that and kept refreshing it, it always came back with the right answer. Could you try it and see? Thanks for the example, it made it so much easier :-)

**Comment by AmiraNagi** [comment]
oh, Thank you so much that really was it :) thanks for your time.

**Comment by rvowles** [comment]
my pleasure!!
