### ISSUE TITLE
(push based) SDK clients are not able to successfully reconnect to Edge server 

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#591]
**Describe the bug**
Given, 
the push based SDK client have established connection with server (and is receiving SSE from edge server)
When,
the edge server restarts (assume some reason here) and comes up again
Then,
the client is not able to establish a connection with the Edge server again (without a restart)

Have tried it with the javascript and the java client. 

The java client, throws following error when the edge server is up again (after restart).

`> 2021-11-19 18:32:57.495  WARN 46879 --- [pool-2-thread-2] i.featurehub.client.jersey.JerseyClient  : Failed to connect to FeatureHub Edge on http://localhost:8085/features/default/b13279a9-1d91-439b-824f-caf752a819ac/lX8rbq2ePg8t37cnWWo56hA3rkVJYG*HyRLA7jzCXZG5xStIMbN, shutting down.
> 2021-11-19 18:32:57.532  WARN 46879 --- [pool-3-thread-4] i.featurehub.client.jersey.JerseyClient  : Failed to connect to FeatureHub Edge on http://localhost:8085/features/default/b13279a9-1d91-439b-824f-caf752a819ac/lX8rbq2ePg8t37cnWWo56hA3rkVJYG*HyRLA7jzCXZG5xStIMbN, shutting down.
`

The javascript client simply stops receiving updates (tried client based key in the browser based react app)

From this point onward, no more updates are received by the clients.

* [] FeatureHub Admin Web app
* [x] SDK
* [] SDK examples
* [] Documentation
* [] Other

**To Reproduce**
1. setup the default docker setup
2. start the (java/javascript) clients that establishes connection with Edge server to receive SSE
 - <ensure everything works as expected up till step 2>
 - javascript/java clients should successfully receive feature updates when the changes are done in the admin console
3. stop the docker instance
4. start the docker instance -- see the error behavior on the client end now 

**Expected behavior**
Perhaps an accidental lose in connection should not enforce clients to restart - to again establish a connection with the server. Perhaps they should auto-magically establish a fresh connection with the edge server - may be on a client's connection timeout or any such error events.

**Comment by rvowles** [comment]
Hi there,

Can you please tell us which versions of the clients you are using?

The JerseyClient is interesting as unless specifically configured to shutdown on edge failure, it won't do so. That log message you are getting is this code: 

`} catch (Exception e) {
        if (shutdownOnEdgeFailureConnection) {
          log.warn("Edge connection failed, shutting down");
          repository.notify(SSEResultState.FAILURE, null);
          shutdown();
        }
      }`

We will check again with the Javascript in browser client, in Javascript you don't get a lot of control, it just keeps trying to connect no matter what :-)

**Comment by mik047** [comment]
Sorry for the delay in response. 

> which versions of the clients you are using
I am using the latest version - [2.3](https://mvnrepository.com/artifact/io.featurehub.sdk/java-client-jersey/2.3) as of this writing.

I was checking the source code and I think the error I pasted happens at a different line -- at the following place.
`if (state == SSEResultState.FAILURE && shutdownOnServerFailure) {
            log.warn("Failed to connect to FeatureHub Edge on {}, shutting down.", fhConfig.getRealtimeUrl());
            shutdown();`
            
Now, I tried replacing `shutdown()` with `init()` and the system behaves as per _my_ expectation.

Let me run you through the problem once again.
Step 1 - Start the docker instance
Step 2 - Started the java client (which on initialization gets updates for all the features it is meant for)
Step 3 - Do some change on admin panel for one of the candidate feature. The client immediately receives SSE and updates its local cache/repository (concurrent hashmap, i think)
Step 4 - Stop the docker instance. The client apparently recognizes the break in connection and goes to the section `"connection closed, reconnecting"`
Step 5 - Start the docker instance. Here is where the client receives a `SSEResultState.FAILURE` and gets into the block I just mentioned above, shuts down the jersey client, and that is it. Any further change in the feature toggles are not received by this client anymore.

All I intend (for my use case) is - that the client should reattempt initializing connection with the server (as the earlier one is  broken - which jersey client gets to know on step 4, 5, and perhaps rightly shuts down.)

For my use case, I attempted to `init()` it after `shutdown()` but that is somehow not working. (May be I am missing something here, but all I intended was to restart the client as if it was the first time - possibly also including to refresh all toggle status as it happens initially)

Then, I simply replaced `shutdown()` with `init()` and seemingly the things are working fine. Can you please fill the gaps that I may be missing.

(Is it possible to do sync communication on some channel?)

JavaScript client is funny, it sometimes able to do what I am trying to do with java sdk on its own, and most time it doesn't.
 Haven't yet analyzed it further.  Just wishing for the similar deterministic behavior in that as well.

**Comment by rvowles** [comment]
Hello again! Its probably worthwhile you join us on our Slack - https://join.slack.com/t/anyways-labs/shared_invite/zt-frxdx34x-ODs_XmLh6BCvqiNeBRx0hA

**Comment by rvowles** [comment]
Ok, so the Java SDK is designed to work like that and its happening because once it reconnects to the server, because there is no cache, it doesn't know about the key being presented and says "hey, it doesn't exist" - so it returns this as a failure. Its designed to do this in case you present a key that doesn't exist or your key becomes stale (such as it being reset). You can prevent this behaviour by deliberately telling the Java client to not shut down on server failure. For Jersey this is:

    final JerseyClient jerseyClient = new JerseyClient(config, true, repository, null);
    jerseyClient.setShutdownOnServerFailure(false);
    config.setEdgeService(() -> jerseyClient);

This is where you are specifically providing your own configured version of the JerseyClient and telling it to have that behaviour rather than letting it discover it for itself.

**Comment by mik047** [comment]
The suggested change does work per the given scenario..
Thanks @rvowles  (y)
