### ISSUE TITLE
MR support for Oracle DB

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#594]
**Is your feature request related to a problem? Please describe.**
The current setup only supports Postgres (and few others) but that does not include Oracle DB (as per the best of what I understand from the docs). I intend to check it to work with Oracle DB as well.

**Describe the solution you'd like**
MR component should work with Oracle DB as well. (May be it is possible and simple enough given MR uses a generic library EBean for interactive with RDBMS)?

**Comment by mik047** [comment]
I am actually ready to test it out. 

So far, I attempted to change the properties file to point to one of the oracle DB instance (with appropriate creds). However, it the docker instance complains of the library not present, as shown below.

`mr-server_1  | {"@timestamp":"2021-11-23T11:22:57.625+0000","message":"failed","priority":"ERROR","path":"io.featurehub.Application","thread":"main","stack_trace":"io.ebean.datasource.DataSourceInitialiseException: Error initialising DataSource with user: jpm url:jdbc:oracle:thin:@localhost:1522/JIOPOC error:No suitable driver found for jdbc:oracle:thin:@localhost:1522/JIOPOC\n\tio.ebean.datasource.pool.ConnectionPool.init(ConnectionPool.java:164) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:153) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPoolFactory.createPool(ConnectionPoolFactory.java:14) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.DataSourceFactory.create(DataSourceFactory.java:26) ~[ebean-datasource-api-7.3.jar:?]\n\tio.featurehub.app.db.utils.CommonDbFeature.configure(CommonDbFeature.kt:135) ~[common-db-1.1-SNAPSHOT.jar:?]\n\torg.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:728) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:736) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:647) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[jersey-common-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:246) ~[jersey-server-3.0.2.jar:?]\n\torg.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:310) ~[jersey-container-grizzly2-http-3.0.2.jar:?]\n\torg.glassfish.jersey.grizzly2.httpserver.HttpGrizzlyContainer$Companion.makeHandler(HttpGrizzlyContainer.kt:9) ~[common-web-1.1-SNAPSHOT.jar:?]\n\tio.featurehub.jersey.FeatureHubJerseyHost.start(FeatureHubJerseyHost.kt:145) ~[common-web-1.1-SNAPSHOT.jar:?]\n\tio.featurehub.jersey.FeatureHubJerseyHost.start(FeatureHubJerseyHost.kt:124) ~[common-web-1.1-SNAPSHOT.jar:?]\n\tio.featurehub.Application.run(Application.java:42) ~[classes/:?]\n\tio.featurehub.Application.main(Application.java:23) [classes/:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjava.lang.reflect.Method.invoke(Unknown Source) ~[?:?]\n\tbathe.BatheBooter.tryMainMethod(BatheBooter.java:149) [bathe-booter-3.2.jar:?]\n\tbathe.BatheBooter.exec(BatheBooter.java:166) [bathe-booter-3.2.jar:?]\n\tbathe.BatheBooter.runWithLoader(BatheBooter.java:125) [bathe-booter-3.2.jar:?]\n\tbathe.BatheBooter.run(BatheBooter.java:115) [bathe-booter-3.2.jar:?]\n\tbathe.BatheBooter.main(BatheBooter.java:37) [bathe-booter-3.2.jar:?]\n\tCaused by: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@localhost:1522/JIOPOC\n\tjava.sql.DriverManager.getConnection(Unknown Source) ~[java.sql:?]\n\tjava.sql.DriverManager.getConnection(Unknown Source) ~[java.sql:?]\n\tio.ebean.datasource.pool.ConnectionPool.createUnpooledConnection(ConnectionPool.java:446) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPool.createUnpooledConnection(ConnectionPool.java:441) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPool.createConnectionForQueue(ConnectionPool.java:660) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:157) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPool.initialiseConnections(ConnectionPool.java:194) ~[ebean-datasource-7.3.jar:?]\n\tio.ebean.datasource.pool.ConnectionPool.init(ConnectionPool.java:162) ~[ebean-datasource-7.3.jar:?]","host":"1b11ff97fd45"}`

I attempted for creating the image myself but could not find the updated doc around it . [This](https://github.com/featurehub-io/featurehub/blob/main/backend/HOW_TO_RELEASE_OS.adoc) is perhaps the closest, but seems out of sync because for example - `cd pipeline/build/base_mr` does not exist anymore.

Can someone guide how to go about this?

**Comment by rvowles** [comment]
Hey there! As you say - we don't include the library for Oracle, but no reason we couldn't, but the database migrations would also need to be built :-) The base_mr should not be being used any longer which is why it doesn't exist, can you give an idea where your build is failing so we can get an idea of where it is going wrong? 

The only issue with supporting new databases is our ability to run them locally to test that the migrations and basic operation of the app is working. Is there a way to do this you could point us to? We don't mind including Oracle support in the basic infrastructure going forward if we are able to make sure it works on each release :-)
