### ISSUE TITLE
Concurrently modify the rules related to a particular feature

### ISSUE THREAD

**Issue by csydvs** [featurehub-io/featurehub#611]
**Is your feature request related to a problem? Please describe.**
Our testing framework uses the MR API (/application/applicationId/feature-environments/featureKey) to update rules on features (turning a feature on for a particular company or user). Because this endpoint takes the entire feature JSON, when we update it concurrently, we often get 409s from the endpoint.

**Describe the solution you'd like**
We'd like a post and a put endpoint at the split targeting rule level so that we can create and update specific rules concurrently with each other. (E.g., POST /application/applicationId/feature-environments/featureKey/targeting-rule and  PUT 
/application/applicationId/feature-environments/featureKey/targeting-rule/targetingRuleKey)

**Describe alternatives you've considered**
This seems like it would be easier than trying to do some sort of intelligent merge on the endpoint, and could hopefully make the UI a bit more robust as well if multiple people are updating it. Maybe there's something nifty could be done for through the edge servers as well, but I'm not familiar enough with the architecture to say.

**Comment by rvowles** [comment]
Thanks for the feedback, the in-real-life feedback we get on usage is very valuable. If you have other ideas and suggestions on making the tool better, please let us know. 

The tricky bit for this will be in the database migration and putting versioning into the rules, so I'll have a think how we can put it into operation. It would be good to have this in sooner. If you are willing to beta-test it in a test environment against your own database, it would be a great help.

**Comment by rvowles** [comment]
This is on the planning board now.

**Comment by csydvs** [comment]
Hey @rvowles, sorry for the slow response, but will be happy to put some work into testing this if it'll be helpful whenever you get into it.

**Comment by rvowles** [comment]
The way that we are approaching this is folding it into the feature value auditing. You will be able to make updates as long as you don't conflict on the default value, retired, locked or individual strategies. So if one person updates a strategy and another one the default value, that will be allowed for instance.

**Comment by rvowles** [comment]
1.6.0 now released allows two non-conflicting features to be merged. Only if two updates conflict on a single strategy or value will the 422 now be issued.
