### ISSUE TITLE
MR Web Downloads canvaskit.js over internet | FH not suitable in Intranet Landscape

### ISSUE THREAD

**Issue by pktsk** [featurehub-io/featurehub#612]
**Is your feature request related to a problem? Please describe.**
We are using FH components for one of our use case. We do not expose services over internet. MR Portal downloads canvaskit.js over internet. Hence, MR Web shows white screen (Screenshot attached)

**Describe the solution you'd like**
MR Web can load canvaskit.js from local.

**Additional context**
MR Web White screen without internet connectivity.
![image](https://user-images.githubusercontent.com/35165140/146489988-24251a6c-b102-42d2-8b33-2df46b63ad43.png)

**Comment by rvowles** [comment]
For our own reference this looks like we can solve this here https://github.com/flutter/flutter/issues/70101

**Comment by rvowles** [comment]
@pktsk could you please contact us directly? We have a spike on this we would like to try out with you? Either via the email on the website or on our Slack. Thanks!

**Comment by IrinaSouth** [comment]
To enable this feature, set in MR application.properties: `web.asset.location=/var/www/html/intranet` 

see docs:
https://docs.featurehub.io/installation.html#_management_repository
