### ISSUE TITLE
Updating log4j library for featurehub 1.4.1

### ISSUE THREAD

**Issue by ariepratama** [featurehub-io/featurehub#617]
**Is your feature request related to a problem? Please describe.**
Hi, I have newly introduced featurehub in my company, and started with featurehub 1.4.1 (starting abt 2 months ago). I used golang and java sdk, and recently, along with other team members.

**Describe the solution you'd like**
I would like to propose bumping log4j library for v 1.4.1 from log4 2.14 to [2.17](https://www.zdnet.com/article/apache-releases-new-2-17-0-patch-for-log4j-to-solve-denial-of-service-vulnerability/)

**Describe alternatives you've considered**
We have tried to bump featurehub version to 1.5.2 esp because of the log4j issue. However, we fail to make the cluster work because somehow either `edge` cannot connect to `dacha` or the `sdk` cannot connect properly to `edge`. We decided to rollback to v1.4.1 because we want to expand our featurehub usage across company first. 

I see that the last version of featurehub sdk for golang is [1.4.1](https://github.com/featurehub-io/featurehub-go-sdk/tree/1.4.1) and there has not been any update for java sdk either.

**Comment by rvowles** [comment]
Hey there, we aren't planning on releasing another version of 1.4.x. We'd like to help you out with the 1.5.x issue however, and recommend you join our Slack channel for direct support. 

Did you add in the configuration to Edge to make it aware of where Dacha was located and what port it was on? 

https://github.com/featurehub-io/featurehub-install/blob/master/docker-compose-options/all-separate-postgres/edge-config/application.properties#L7

Our Slack is here: https://join.slack.com/t/anyways-labs/shared_invite/zt-frxdx34x-ODs_XmLh6BCvqiNeBRx0hA

**Comment by ariepratama** [comment]
we did add `dacha.url.default` configuration edge application config. But still cannot manage to get it work, any recommendation on what logs to check on?

**Comment by rvowles** [comment]
If you can exec into the running docker instances you can edit the /etc/common-config/log4j2.xml file  - remove the commented section, it is designed to pick up changes in 30 seconds, so it will then start sending out considerable logging including all incoming traffic. I would do it on Edge first. There was a health check bug on 1.5.1 where unless the logs were at debug level, the health check wouldn't work but that was fixed in 1.5.2 (along with log4j2 2.16).

**Comment by rvowles** [comment]
Hey - we have two companies who have confirmed 1.5.x works ok for them, so if you are able to make it onto our Slack so we can help you out? :-)

**Comment by ariepratama** [comment]
conclusion: my `dacha` setup includes `run.nginx` in `common.properties`, for some reason it has hinder the connection to `dacha` application. Removing `run.nginx` totally (setting it to false will still produce same result) will solve it. Thanks @rvowles !

**Comment by ariepratama** [comment]
related issue: https://github.com/featurehub-io/featurehub/issues/623
