### ISSUE TITLE
Dacha/MR can get out of sync when Dacha is starting up - once it has started everything is fine

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub#628]
If Dacha is requesting a cache and the MR it selected fails to provide it, and then gets shut down, the Dacha instance will keep asking that instance for the cache rather than going back to square one and negotiating a new master.

**Comment by cspalding** [comment]
I have a question related to this (maybe tangentially). I'm happy to open a separate issue but I figured I'd check in here first. I see the [ServiceMonitor](https://github.com/featurehub-io/featurehub-install/blob/main/helm/featurehub/templates/dacha/servicemonitor.yaml) that Dacha's Helm Chart has, but I'm not clear on what metrics are emitted via the `ServiceMonitor`. 

Is there any documentation on what metrics are emitted via the `ServiceMonitor`? In particular, I'm interested in monitoring cache propagation.. would I do that in my system by looking at the time it takes for a Kubernetes container running Dacha to get from the `ContainerCreating` status to the `Running` status?

Apologies if this is the wrong place for this question @rvowles!

**Comment by rvowles** [comment]
When Dacha starts, it essentially negotiates a master node and then asks the MR to publish all its environments and service accounts - they publish how many they have, along with each record, so Dacha knows when it has the whole set. The health check monitors that a dacha is "at rest" - that it has everything it thinks it should have. New metrics will come in 1.5.9 that tell you how many of these it has, how many MR has and so forth that let you detect anomalies between Dacha instances - but I would say your metric is good for the question you ask?

**Comment by cspalding** [comment]
Ah, I see. Thanks for clarifying!
