### ISSUE TITLE
Enabling change logs on entities for app level auditing

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#644]
**Is your feature request related to a problem? Please describe.**
Need audit logs in the FH system. It is already in a roadmap and hopefully will be picked soon. In the meantime, is it possible to enable the logging (which is configurable) for any changes made to the relevant/all entities.

**Describe the solution you'd like**
If you accommodate enabling [this](https://ebean.io/docs/features/changelog)  on relevant entities, which one can enable/configure in the property file, would enable tracing of changes made to an entity.

**Comment by rvowles** [comment]
So I have a draft MR for this @mik047  - the log format looks like this: 

"ts":1642928906424,"change":"U","type":"DbFeatureValue","id":"c1a9777e-c688-4e0e-95fa-cacc2297ba14","userId":"68c09a3d-6e44-4379-bfc1-3e75af59af38","userContext":{"email":"irina@i.com"},"data":{"whenUpdated":"2022-01-23T22:08:26.424","version":4,"locked":true},"oldData":{"whenUpdated":"2022-01-23T22:08:26.406","version":3,"locked":false}}

As long as you have enabled user audit logging, it picks up  the user and adds who did it.

The only issue I see with this in a k8s cluster is that it needs to stream to a different log - and in a standard cluster your logs go to stdout and are captured from there. Do you have some ideas on how this would work for you? Is there a log4j2 driver I should include to allow it to be shipped by some protocol you use?

**Comment by mik047** [comment]
The immediate need is to persist the logs for a later analysis, in case of incidents. So, perhaps we can stream it to a file (which can be stored in a mounted volume in k8s). Eventually, it needs to be integrated with a centralized log aggregator; either via direct TCP call OR via a log forwarder. Maybe there log4j2 driver will become handy.
