### ISSUE TITLE
Adding last login details on the Dashboard

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#662]
**Is your feature request related to a problem? Please describe.**
Wish to add `last login details` in the `Dashboard -> Users -> Details` page as shown in the screenshot.
<img width="1460" alt="Screenshot 2022-01-21 at 12 58 22 AM" src="https://user-images.githubusercontent.com/5581890/150408977-4c67cf95-8def-4db1-8c6d-26e373ccbba5.png">

**Comment by IrinaSouth** [comment]
will take a look at the front-end
