### ISSUE TITLE
OAuth2 Integration with Self-Managed OAuth Service

### ISSUE THREAD

**Issue by pktsk** [featurehub-io/featurehub#673]
**Is your feature request related to a problem? Please describe.**
We are using feature-hub for our internal use. For the same, we want to allow only organisation employees of mine to login to MR Web. 

We do not have Google, Azure or Github OAuth provider.

**Describe the solution you'd like**
We have self-managed OAuth service which we wan't to enable in MR Web.

**Describe alternatives you've considered**

**Additional context**

**Comment by rvowles** [comment]
Hi there! 

So is the IdP you are running a custom one? For each integration we have needed to know what information to use to construct the urls, then the token callback is usually standard but the understanding of that token is the difficulty. Is the access token a JWT? We need at least the email address to be available from that jwt if so.

Further, what icon so you expect on the front? We should make that part of the configuration?

Would you be willing to test it on your side for us?

Feel free to get in touch with us on our Slack as well!
