### ISSUE TITLE
Ability to search/filter the features on UI

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#675]
**Is your feature request related to a problem? Please describe.**
Currently, if the features grows beyond a screen size, it is difficult to navigate among the features. 

**Describe the solution you'd like**
Would be nice to have an ability to search/filter the features on UI. It should also be able to search/filter across feature types (flags/string/number/json).

**Describe alternatives you've considered**
Maybe the following will do the trick.
- putting Search/Filter box along the lines of "Feature Flags", "Feature Values", "Configurations"
- typing the text will auto populate the matched names
- selecting one of them will result populating that in the details section while auto selecting the type (Flags/Values/Configurations)

<img width="1792" alt="Screenshot 2022-01-26 at 11 49 06 AM" src="https://user-images.githubusercontent.com/5581890/151114108-c0e08475-ca35-474e-97f7-085508d216b2.png">

**Comment by IrinaSouth** [comment]
closing and this will be available in v1.6.0
