### ISSUE TITLE
Click-ability for the features with reference link

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#677]
**Is your feature request related to a problem? Please describe.**
Adding a feature asks for an optional reference link. If provided, getting to that link requires multiple clicks/tasks to reach to that link, as follows
 - clicking on more section for that feature (the three dots)
 - clicking on view details
 - copying the link
 - copy/pasting the link in the new tab

**Describe the solution you'd like**
Ability to click the name of the feature

**Describe alternatives you've considered**
May the following will do the trick
- if the reference link is provided, then allowing an ability to click the name to open that link

**Additional context**=
From the security standpoint, **may be** more measures are required to be incorporated, such as - sanitizing input for sql injection or scripting attacks.

<img width="1791" alt="Screenshot 2022-01-26 at 11 05 41 AM" src="https://user-images.githubusercontent.com/5581890/151118758-61385f55-618e-4447-aab6-824c520963c9.png">

**Comment by IrinaSouth** [comment]
Added an icon for this. Merged to main.
