### ISSUE TITLE
Storing Headers in NATS, Dacha and Edge logs

### ISSUE THREAD

**Issue by shrish789** [featurehub-io/featurehub#691]
**Is your feature request related to a problem? Please describe.**
The headers(ex- api key, XFF, etc) which are being stored in MR are not carried forward with the call and hence not stored in the logs of NATS, Dacha and Edge server.

**Describe the solution you'd like**
The headers should be carried forward with the call to other servers and hence should be stored in the logs of other servers too.

**Comment by rvowles** [comment]
This will be closed when we release the next version as it was addressed using W3C Baggage headers and documented here https://github.com/featurehub-io/featurehub/commit/fad1c0453c4adfae9b7d07ba0133bd72a4c25fc7

**Comment by rvowles** [comment]
This is now in 1.6.3 which has been released.
