### ISSUE TITLE
Last login details not showing and all users are getting access to FeatureHub

### ISSUE THREAD

**Issue by shrish789** [featurehub-io/featurehub#698]
**Describe the bug**
1. Last Login details are not shown for the users who have logged in using Google/Github/Jio(Our Employer). The details are being shown for those users who have been created by the super-user.
2. Every user is able to login into FeatureHub right now but it should only be allowed to those who are already created in the system by super-user or admin.

 Which area does this issue belong to?
FeatureHub Web Admin app.

**To Reproduce**
1. Login using Google/Github/Azure
2. Check the last login details of the above user. {The details would be empty}

**Expected behavior**
1. Last login details should be visible for all users
2. Only those users should be granted access to Site which are already created

<img width="1680" alt="Screenshot 2022-02-04 at 11 36 13 AM" src="https://user-images.githubusercontent.com/44712688/152481265-52f0d98b-70bb-41d4-91fe-ea9e9d7cdead.png">

**Versions**
 - FeatureHub version [1.5.7-RC-oauth-generic]
 - OS: [iOS]

**Comment by IrinaSouth** [comment]
1. Definitely an issue for external oauth providers users. 
2. This is expected, there is a setting in the mr properties file to disable such behavior by setting  auth.userMustBeCreatedFirst=true. (false by default). However there is a related bug https://github.com/featurehub-io/featurehub/issues/452

**Comment by IrinaSouth** [comment]
both fixes are now in docker version [1.5.7-RC]

**Comment by shrish789** [comment]
Thanks for fixing these issues.
