### ISSUE TITLE
Support for making a feature invisible/unset per environment

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#707]
**Is your feature request related to a problem? Please describe.**
Once the feature toggles are consumed, the general idea is to merge the code and make the toggles disappear from the code base. Before reaching to production, there requires a way so that it can be tested in lower environments.

Currently, the toggles are application wide and can only be managed at that level (for a right reason though, so that we don't have to manage per environment separately and get into manual errors etc.) But that also makes the tests related to removing toggles difficult.

**Describe the solution you'd like**
Introduce a mechanism so that a feature toggle is invisible for an environment. So the testing could be possible as and when the toggle (to be removed) moves in the release work flow from lower to higher environments. [Thanks Richard for suggesting such a mechanism]

This would also help, in case a rollback needs to happen. Deleting would make it impossible to bring it back, however, invisible toggles can be brought back by making it visible, if the rollbacks happen.

**Comment by rvowles** [comment]
We have decided to call this "Feature Retirement" as it is intended to support the end of a feature's lifecycle.

**Comment by IrinaSouth** [comment]
Need to update docs once this is implemented 

- [ ]
