### ISSUE TITLE
Providing a way to tag toggles with some additional context

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#719]
**Is your feature request related to a problem? Please describe.**

We need to have some means by which we can tag toggles so that we can better integrate FHIO (for our custom needs), starting with the needs around

- CI/CD (mapping toggle to a deployment component in build and release, automatic promotion of toggle state based on test sign-offs in lower environments, etc.)
- and showing health metrics (of how well the teams are using it, etc.)

**Describe the solution you’d like**

Add an additional field per toggle (say “description”) which can hold any text value in it (we intend to use it to store some random KV pairs as per our need). One can add random value in here as per requirement.

**Describe alternatives you’ve considered**

Had initially thought of using “reference link” for this purpose but rejected that idea cause

- existing users may well be using it for storing links and we do not wish to break that semantic contract (who knows, the future version of FHIO might as well add validation to make sure it is indeed a url link, it can help in 677 as well)
- we ourselves use that field for storing a link to our own tracking tool - Azure DevOps

Another alternative could be 

- to allow list of Key-Value pairs allowed to be tagged to a toggle. However, that would mean more work in UI and API and not sure if that is appropriate for audience/users at large.
- _Note_: Tagging here not only just means attaching a value (e.g. something like “abc”). In our case we mean tagging as attaching a key-value (e.g. something like foo=“bar”) so as to facilitate “context=value” scenarios.

**Additional context**

1. It has ripple effect on the API and UI.
- API needs to include this in the response payload (so that the integrating tools can utilise as and when needed)
- UI can show it under “Details” section below “Reference Link” (Just a thought. A UX may give a better alternative)

2. Not sure of the exact length it requires to have in DB but should surely not be a smaller value (e.g., surely not a length suitable for, say, storing a first name; but something reasonably large enough to store multiple tags).

**Comment by rvowles** [comment]
I believe  this is done, I will close and please re-open if it is not!

**Comment by mik047** [comment]
Yes it is.. Thanks Richard. :)
