### ISSUE TITLE
FeatureHub MR not able to connect to MySQL DB

### ISSUE THREAD

**Issue by shrish789** [featurehub-io/featurehub#753]
**Describe the bug**
We are not able to connect from FeatureHub's MR to MySQL DB set in another server. Please find the screenshot given below for the exact error we are facing.

 Which area does this issue belong to?
FeatureHub

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup MySQL DB on another server
2. Mention the JDBC connection string in the app-config.yaml file
3. After starting the servers, MR is facing issues in connecting to MySQL DB

**Expected behaviour**
MR should be able to connect to MySQL DB

**Screenshots**
<img width="1291" alt="Screenshot 2022-03-22 at 5 23 34 PM" src="https://user-images.githubusercontent.com/44712688/159851583-bf5f569a-a343-450b-ac73-bf4d0cb82d3a.png">
<img width="1678" alt="Screenshot 2022-03-24 at 11 33 56 AM" src="https://user-images.githubusercontent.com/44712688/159854968-a07e65be-e860-4aa3-aa6a-c77185019144.png">

**Versions**
 - FeatureHub version [e.g. 1.5.7-RC]

**Comment by rvowles** [comment]
Believe this is an issue with MySQL 5.x - MySQL 8 verified to work fine.
