### ISSUE TITLE
Allowing (use of) Admin API when OAuth is enabled

### ISSUE THREAD

**Issue by mik047** [featurehub-io/featurehub#760]
**Is your feature request related to a problem? Please describe.**
When OAuth is enabled, using Admin API will no longer work based on username/password combination.

**Describe the solution you'd like**
[none yet but tokens are industry standard for such cases]

**Describe alternatives you've considered**
[none yet]

**Comment by rvowles** [comment]
We are going to do this with Admin Service Accounts. These will be people accounts that are surfaced in a different set of tabs, but act more like GCP service accounts - they will be able to have their own group allocations and permissions and will only be able to be used via a API Key.

**Comment by rvowles** [comment]
This is in 1.5.8
