### ISSUE TITLE
Create React SDK for FeatureHub

### ISSUE THREAD

**Issue by thedanchez** [featurehub-io/featurehub#791]
**Is your feature request related to a problem? Please describe.**
Considering the popularity of major UI libraries/frameworks out there (e.g. React), I feel there should be SDK implementations for these commonly used libs to reduce friction on adopting FeatureHub for consumers.

**Describe the solution you'd like**
I would like to see React specific things for FeatureHub provided (probably in a separate package) that export custom React Hooks that devs could use (e.g. `useFeature`). Also, would like to see the documentation updated for React to reflect this. The current React examples still use class-based components and things have moved on to functional components using React Hooks.

**Describe alternatives you've considered**
[GrowthBook](https://docs.growthbook.io/) is looking like it's going to be a major competitor to FeatureHub soon (if not already) and they provide many of the major options for devs to use (like their [React SDK](https://docs.growthbook.io/lib/react)). Their API looks incredibly pleasant to use and feels like it streamlines the DX.

Once they supply the ability to configure multiple DB options aside from MongoDB (i.e. MySQL, Clickhouse, Postgres) I suspect customers would start considering them since they provide these streamlined API tools out of the box for ease of adoption.

**Comment by rvowles** [comment]
Not having a React expert on the team always slows these things down, but it's a good idea! I'll see what we can do.

Growthbook approaches things from a different angle being more of an Optimizely clone, and it wasn't built for scale, FeatureHub was always built for cloud first and scale. Growthbook has very good analytics support for what is going on with your features, and it's backed by Y Combinator, so they actually have a fair bit of funding.

**Comment by IrinaSouth** [comment]
Closing as we have now released dedicated  https://www.npmjs.com/package/featurehub-react-sdk and https://www.npmjs.com/package/featurehub-solid-sdk
