### ISSUE TITLE
Individual create, edit and delete features right

### ISSUE THREAD

**Issue by loicoudot** [featurehub-io/featurehub#802]
**Is your feature request related to a problem? Please describe.**
Enhancement proposal: On 'Applications settings' panel, it could be great to separate:
- This group can create features for this application
- This group can edit and delete features for this application

**Describe the solution you'd like**
Why not two checkboxes instead of the one which regroup create, edit and delete rights

**Describe alternatives you've considered**
N/A

**Additional context**
First, thank you for this great project: easy to use, great functionalities and high quality java client!
Our use case:
We would like to give our developers the ability to create features directly in the UI of FeatureHub. 
But we also want to avoid manipulation error by deleting an existing feature.
Features can already be used in a production environment, and deleting a feature or editing the 'Feature Key' will break the production environment.

**Comment by rvowles** [comment]
Hiya! We have seen this, understand the request 👍
