### ISSUE TITLE
Follow and contribute to OpenFeature initiative

### ISSUE THREAD

**Issue by siraj-mx51** [featurehub-io/featurehub#821]
**Is your feature request related to a problem? Please describe.**
Consider if FeatureHub can contribute/adhere/work-towards-adhering to the [OpenFeature initiative](https://www.dynatrace.com/news/blog/new-openfeature-standard-for-feature-flagging/) submitted to CNCF.

**Describe the solution you'd like**
FeatureHub looks like it is well positioned to contribute to a community driven project to drive standardizing feature-flagging.

**Describe alternatives you've considered**
Not applicable

**Additional context**
[Interested Parties](https://github.com/open-feature/community/blob/main/interested-parties.md#interested-organizations)
[Spec/Spec Draft](https://github.com/open-feature/spec)

**Comment by rvowles** [comment]
Thanks for the heads up on this, we already use the W3C Baggage concept to allow for feature flagging overriding and encourage the use of OpenTelemetry to take advantage of this, so we will definitely look into it.

**Comment by siraj-mx51** [comment]
@rvowles i believe this is more about standardizing feature flagging APIs & SDKs regardless of the vendor.

**Comment by rvowles** [comment]
Oh dear. Closer examination shows they have already headed down the awful path that LaunchDarkly took, we looked at that API style and deliberately chose an alternative path. It seems too late for us to reasonably contribute, only to create adapters  :-(

**Comment by siraj-mx51** [comment]
Not sure why this and the go-sdk issue were marked as completed, is this part of featurehub now or is this being tracked somewhere else ?
