### ISSUE TITLE
Per environment create/change/delete features permission management

### ISSUE THREAD

**Issue by UnaiUribarri** [featurehub-io/featurehub#837]
**Is your feature request related to a problem? Please describe.**
Developers of an application should be able to create, change and delete features in staging environments (alpha & beta) but not in prod.

**Describe the solution you'd like**
Feature management permission can be granted per environment, to protect prod environment from unexpected changes.

**Describe alternatives you've considered**
The alternative is not allowing developers to create, change and delete features and ask them to open a ticket to the admin even for operations in alpha stage.

**Additional context**

**Comment by IrinaSouth** [comment]
Hi @UnaiUribarri, 

Thanks for creating the request. 
Just to confirm, you are requesting Create/Edit/Delete permission on a feature to be per environment. 
The fundamental rule we have around features is that once feature is created, it always created in every environment. The same goes for deleting a feature. We are not planning to change this approach, however we are thinking to split the permission as suggested in this ticket https://github.com/featurehub-io/featurehub/issues/802.   This will give you the additional safety to isolate who can have the permission to edit or delete a feature.  Hope this can be a suitable solution for your problem. Cheers!

**Comment by UnaiUribarri** [comment]
After experimenting a bit, I realise that what I want is to prevent to delete features that are locked in any environment where the current user cannot unlock them.

For example, if a feature is locked in production and current user cannot unlock it, he should not be able to delete it neither.

**Comment by UnaiUribarri** [comment]
I will close this issue and open a new one with the right feature.
