### ISSUE TITLE
Disallow deleting locked features

### ISSUE THREAD

**Issue by UnaiUribarri** [featurehub-io/featurehub#860]
**Is your feature request related to a problem? Please describe.**
We have two groups: admins and devs. Both can create, edit and delete features.
The different is that admins can unlock and change features in production environments and devs cannot.

In this scenario, I expected that locked features can only deleted by admins, since deleting it may change the app behaviour, but developers can also delete them.

**Describe the solution you'd like**
1. Do not allow to delete features that are locked in any environment.
2. Do not allow to delete features if current user cannot retire them from all environments where it is not yet retired.

**Describe alternatives you've considered**
Another option is to separate create, edit and delete feature permissions, and do not grant deletion permission to devs.
In any case, I think it is reasonable to disallow deleting features that are locked or when the current user is not allowed to retire them.

**Additional context**

**Comment by IrinaSouth** [comment]
Hi @UnaiUribarri, 

Cheers for describing your request. We have a similar request here that we are planning to do https://github.com/featurehub-io/featurehub/issues/802
