### ISSUE TITLE
Cannot login using OAUTH2 after user deletion.

### ISSUE THREAD

**Issue by ilyatovbin-pp** [featurehub-io/featurehub#877]
**Describe the bug**
If an OAUTH logged in user is deleted, that user cannot login again. He gets redirected back to the login page after pressing "Sign in with XXXX"
In the admin UI you can see the user being recreated with all their previous settings (groups).

 Which area does this issue belong to?

* [X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Configure OAUTH login
2. Login once with a user.
3. Login with an admin user and delete that user.
4. Try to login again with the first user.

**Expected behavior**
A new user is created without settings in the app and the user can login again.

**Versions**
 - FeatureHub version 1.5.9
 - SDK version
 - OS: [Linux]
 - Browser [Chrome]

**Comment by IrinaSouth** [comment]
thanks @ilyatovbin-pp for reporting this. We will add this to our priority list to fix.
