### ISSUE TITLE
Featurehub 1.5.6: Potential memory leak on edge service

### ISSUE THREAD

**Issue by ariepratama** [featurehub-io/featurehub#895]
**Describe the bug**
Potential memory leak at featurehub edge server (see the screenshot). 

 Which area does this issue belong to?

* [x] FeatureHub Edge server

**To Reproduce**
TBF

**Expected behavior**
This potential memory leak should not happen.

**Screenshots**
<img width="1446" alt="Screenshot 2022-12-04 at 1 23 46 PM" src="https://user-images.githubusercontent.com/4386182/205477235-642a44ab-85fe-4054-b7f4-2e414f3da908.png">

**Versions**
 - FeatureHub version 1.5.6

You can get the version of the FeatureHub container by running ```docker ps``` command.
Please include the OS and what version of the OS and Docker you're running.

**Additional context**
One of my team set json configuration as big as 8-9kb, and this is the first time we did this. It seems like the issue correlated with this json configuration setting

**Comment by rvowles** [comment]
What happens when it drops? Has the pod crashed?

**Comment by ariepratama** [comment]
the pod crash and it will restart by itself, has anyone encounter this issue before and will upgrading the version work? I'll try to profile the jvm, which I do not have access right now.

**Comment by ariepratama** [comment]
oh is there an easy way to enable the jmxremote setting on featurehub's image? 😄 I figure, otherwise, I have to create my own docker image to do this

**Comment by rvowles** [comment]
1.5.6 is from January of this year and a lot has changed in  that time, but I can profile it outside of the JVM here. Anything you put into the application.properties gets loaded into system properties so that might help you?

**Comment by rvowles** [comment]
It seems very unusual though because Edge does not maintain any state apart from that there is a connection, so I'm scratching my head...

**Comment by rvowles** [comment]
So I ran up some extensive testing on 1.5.10 using YourKit Profiler, I used a JSON object of 8k and I did see the Eden Space slowly increase but then regularly drop. I can see from older Jackson libraries that there was a memory leak. The deserialisation of the large object would take a fair amount of memory to collect and pass through, but those requests are concentrated its not a 1 Edge request, 1 Dacha request to get the data. Whats interesting is you aren't seeing the same issue on Dacha? You would think as it serialized the data out it might have an issue. 

One other question - are Dacha and Edge communicating on your system via NATs or via REST?

**Comment by ariepratama** [comment]
I am using all separate with postgres + NATS publishing . No dacha is fine 😄 so not quite sure too. 

`I can see from older Jackson libraries that there was a memory leak`, I see, then upgrading might solve this?

did you profile from container or from running on featurehub directly on your local ?

**Comment by rvowles** [comment]
I tried running it from my local, but I would definitely upgrade as a  lot of libraries have received a bump and it may be an issue in one of them around this kind of edge case.

**Comment by rvowles** [comment]
If you can let me know whats up with this ticket as I am keen to help before I head away for holidays.

**Comment by ariepratama** [comment]
@rvowles hey, sorry I had to monitor for a few (3d) days. But I think my guess is right, there's something leaking when using json feature values. Now we have delete those values, it is stable

**Comment by rvowles** [comment]
@ariepratama did you try upgrading to 1.5.10?

**Comment by rvowles** [comment]
Hey, no further feedback on this so I will close it out. Please re-open when you upgrade and you see an issue, thanks!
