### ISSUE TITLE
paginate list of features and search features

### ISSUE THREAD

**Issue by ilyatovbin-pp** [featurehub-io/featurehub#896]
**Is your feature request related to a problem? Please describe.**
I've migrated some of our feature flags to featurehub for testing. currently around 900 of them (A. that's for 1 environment, and we have more. B. that's not all of the flags we have).
When loading the list from the web UI, it's very slow to load, and then you get a huge, long, laggy page. 

**Describe the solution you'd like**
1. Add pagination, to load N results, and a list of pages
2. Add an option to search for features containing a certain name.

**Describe alternatives you've considered**
at the moment I'm using a python script utilising the REST API to migrate / control features so I don't care much for the UI but we need our regular users to be able to use the UI and at the moment it's usable but pretty bad.

**Comment by IrinaSouth** [comment]
similar to https://github.com/featurehub-io/featurehub/issues/676

**Comment by rvowles** [comment]
Hey there, as @IrinaSouth has mentioned, please review #676 and if it is the same, please feel free to close this one and add any extra details you might find useful to that ticket :-) Thanks!

**Comment by ilyatovbin-pp** [comment]
Yup, correct. closing.
