### ISSUE TITLE
Push based Webhooks for driving Automation

### ISSUE THREAD

**Issue by rvowles** [featurehub-io/featurehub#902]
To drive the ability to push automation based changes, particularly around FaaS systems that need to respond to feature changes, the system should allow the user to, per environment, have updates to features pushed to a webhook. 

This requires:

- when feature updates are published they should be enriched and republished. It is too much of a load on  the MR to collate all of the information about an environment and its current feature set, so this can be done by Dacha. This also sets the stage for further use cases of event based activities in FeatureHub that need a stream of fully formed updates.
- a webhook service (we will choose edge) needs to POST the body of the enriched data out to the recipient using a CloudEvent using the URL and headers provided by the user
- the result of the POST and what was sent needs to be bundled up and dropped on a queue so a running MR can store it
- webhooks need to be optionally enabled
- enrichment needs to be optionally enabled
- if they are enabled the front end needs to make Webhooks react to whether it is configured. If it is configured, it should add another Application tab to allow users to see/edit the Environment configuration, look at the webhook results and examine their details
- public MR API needs updating for new API endpoints
- Cloud events (enriched data + webhook results) need definition
- on a configurable level of failure, the webhook should be disabled - if the endpoint fails X times in a row, the system should automatically disable it

**Comment by rvowles** [comment]
![image](https://user-images.githubusercontent.com/55768/207537518-3fbb0e36-c61e-4823-b99f-b888902d23ff.png)

**Comment by rvowles** [comment]
![image](https://user-images.githubusercontent.com/55768/207537662-c93b3593-4e70-450e-bce4-24f972fe8e8c.png)

**Comment by ilyatovbin-pp** [comment]
Can be great for alerting purposes as well.
We definitely want to configure "Slack Alerts",so when someone changes values everyone knows features are enabled or disabled.
This means we would also like to have some sort of "template" that modifies the POST payload to the Webhook.

**Comment by rvowles** [comment]
@ilyatovbin-pp CloudEvents -> https://cloudevents.io - but we have a new Javascript Admin SDK and Webhook SDK which reflect the OpenAPI documents used to generate the data  that is sent.
