### ISSUE TITLE
Feature - Slack integration

### ISSUE THREAD

**Issue by IrinaSouth** [featurehub-io/featurehub#913]

**Comment by rvowles** [comment]
This feature consists of the following parts (as at time of writing):

- update the base auditing capability introduced in 1.6.0 (which as of 1.6.1 is now enabled), and have it collect the changes that were made as part of the update. ✅  This work was completed in : https://github.com/featurehub-io/featurehub/commit/387123fbbb969bd416c5e615aa9fafbe5686386d
- add a new async cloudevent, and add code that converts the internal data into the cloud event. It should publish this internally as a cloud event.
- add a configuration process and code supporting the ability to deliver that cloud event on one or more registered channels.   Allow enabling a NATS publisher with configurable channel, a Kinesis stream with configurable channel, a Pub/Sub topic with configurable topic name, or a webhook with a configurable destination and headers.
- add customisable encryption common layer where the customer must specify the key, and builds APIs to allow individual environments to configure Webhooks (webhook url (which should be encrypted), (type should be detected via the webhook url)). Future configuration can enable for formatting, events of interest and so forth.
- build webhook container compatible with cloud functions, azure functions, lambda, etc that is able to process the message, format it correctly and deliver it to the specified webhook (in featurehub messaging)
